### ISSUE TITLE
Joda is not quite ISO-8601 compliant (org.joda.time.format.ISODateTimeFormat.dateTimeParser)

### ISSUE THREAD

**Issue by luis-ortiz** [JodaOrg/joda-time#112]
To quote http://en.wikipedia.org/wiki/ISO_8601 "There is no limit on the number of decimal places for the decimal fraction."

Python style DateTimes have microsecond, not millisecond precision like:

2014-01-17T15:57:22.105710Z

It would nice if Joda was more tolerant and accepted any number of decimal seconds and rounded the microseconds up to the nearest millisecond.

Logstash is currently using the Joda for its date/time parsing and I have to pre-process all timestamps originating from Python applications to force the fractional seconds to just 3 digits of precision, which is rather annoying.

**Comment by wigbam** [comment]
Expanding more on this topic - currently there is no way to create an ISO-8601 compliant date format with a configurable decimal portion using the `ISODateTimeFormat` class. So it is impossible, for example, to create a printer which would always print up to 6 decimals for seconds.

So the natural next best option is to try and create your own date format based on the existing formats provided by `ISODateTimeFormat` class. But even then, while it is possible to re-use date formats, utility methods creating time formats effectively "close" the format builder by appending time zone offset. So what many end up doing is copy-pasting utility methods time format related code from `ISODateTimeFormat` class into their own codebase with a few modifications.

This is quite a nuisance and would be nice if `ISODateTimeFormat` would allow to specify required decimals if not on the top-level methods like `dateTime()` but at least for individual time format methods.

**Comment by jodastephen** [comment]
The approach in Joda-Time is that you need to use `DateTimeFormatterBuilder` if one of the standard formatters is insufficient. Since the builder is sufficient here, I'm closing the issue, as I don't want to add more to `ISODateTimeFormat`.
