### ISSUE TITLE
Joda time can't handle large intervals for seconds

### ISSUE THREAD

**Issue by trhura** [JodaOrg/joda-time#117]
I am getting this error when I use Joda in `clojure` via [clj-time](https://github.com/clj-time/clj-time/). 

``` clojure
user> (in-seconds (interval (now) (-> (*  3 1000) years from-now)))
ArithmeticException Value cannot fit in an int: 94670812800 org.joda.time.field.FieldUtils.safeToInt (FieldUtils.java:190)
```

And it seems that Joda is assuming seconds field to be an int, so large interval values doesn't work.

related bug: https://github.com/clj-time/clj-time/issues/104

**Comment by cmal** [comment]
whops
