### ISSUE TITLE
Please fix the license!

### ISSUE THREAD

**Issue by psionn** [JodaOrg/joda-time#193]
Would love to include the license in a project, but it's missing critical information including the name of the copyright holder and the year.

   Copyright [yyyy] [name of copyright owner]

This is present in both the website and git repo.

**Comment by seniath** [comment]
I've spoken to my legal team regarding this issue, and they got back to me with the following response;

"well he’s right in saying he can put copyright info in the NOTICE file, but if you read the bottom of http://www.apache.org/licenses/LICENSE-2.0.html it says the NOTICE file has to contain the license."

Would it be possible to update the NOTICE file accordingly?

**Comment by jodastephen** [comment]
See http://www.apache.org/dev/licensing-howto.html, all Apache projects are
licensed this way.
