### ISSUE TITLE
Feature: date.withTime(other: DateTime)

### ISSUE THREAD

**Issue by zebraitis** [JodaOrg/joda-time#213]
now i have to do : 

date.withTime(time.getHourOfDay, time.getMinuteOfHour, time.getSecondOfMinute, time.getMillisOfSecond)

I think it could be very useful overload method withTime in class DateTime

public org.joda.time.DateTime withTime(DateTime other) {
           return withTime(other.getHourOfDay, other.getMinuteOfHour, other.getSecondOfMinute, other.getMillisOfSecond) 
}

Great job! greetings.
Pablo

**Comment by jodastephen** [comment]
I've added two methods based on your proposal. You will be able to do

    date.withTime(dateTime.toLocalTime())
