### ISSUE TITLE
in LocalDate.fromDateFields blocking/waiting in mutli-thread environment

### ISSUE THREAD

**Issue by tcmak1** [JodaOrg/joda-time#219]
Hi the following works fine in single thread environment.
But when run in mutli-thread, it is blocking and waiting for LocalDate.fromDateFields for each thread....
and result in very slow response .... Any work around for that ?

public static String format(Date inDate) {
                DateTimeFormatter fmt = DateTimeFormat.forPattern(dateFormatStr);
                LocalDate jodaDate = LocalDate.fromDateFields(inDate);
                    return jodaDate.toString(fmt);
}

**Comment by jodastephen** [comment]
The source code of `LocalDate.fromDateFields()` contains no synchronization or locking. The issue is within the JDK `Date`/`Calendar` methods that are called, which joda-time cannot change.

**Comment by tcmak1** [comment]
I have try using the following method "DateTime jodaDate = new DateTime(inDate);" instead of "LocalDate jodaDate = LocalDate.fromDateFields(inDate);" which is no locking issue. However, there is 1899 issue ...... So i look for other alternative or not ....
