### ISSUE TITLE
Create build of joda-time without TZ data included

### ISSUE THREAD

**Issue by dlew** [JodaOrg/joda-time#220]
The core problem that [joda-time-android](https://github.com/dlew/joda-time-android) solves is completely avoiding `ZoneInfoProvider` due to memory issues it causes on Android.

Ideally we'd just link joda-time as a dependency, but it was not feasible before. `ZoneInfoProvider` was unavoidable because of the static call `setProvider0` that used to exist. But I've noticed that in 2.6, all loading is lazy now, thus we would be able to insert our own provider before joda-time chooses its defaults.

I'm interested in doing the Right Thing and including joda-time as a dependency but there's one more issue: JAR size. joda-time-android still needs to use our own provider with resources delivered by Android itself. If I use joda-time as a dependency then I'll be including all the resources 2x, which is a lot of extra space for an app.

I was wondering if it would be feasible to create a version of joda-time that didn't include the TZ resources. Identical build, just minus that directory.

This is related to #37, but takes a different tact (rather than redefining where the resources are, removing them altogether so you can depend on your own provider).

**Comment by jiongxuan** [comment]
+1 too!

**Comment by jodastephen** [comment]
Can you check this branch and decide if the jar file produced with classifier "no-tzdb" would meet your needs? I won't merge this branch unless you confirm ;-)

**Comment by dlew** [comment]
Sounds good - I'll verify sometime in the next week.

**Comment by dlew** [comment]
I've just run through some tests - it definitely looks like it'll work!

**Comment by jodastephen** [comment]
v2.7 available on Maven Central, depend on joda-time with the "no-tzdb" classifier through maven.
