### ISSUE TITLE
DateTimeZone.forID(String) returns wrong dtz for 196 of 582 available IDs

### ISSUE THREAD

**Issue by er2** [JodaOrg/joda-time#224]
Here's the unit test I used to find this bug

    @Test
    public void testTZ() {
		Set<String> tzs = DateTimeZone.getAvailableIDs();
		for (String tz : tzs) {
			DateTimeZone dtz = DateTimeZone.forID(tz);
			if (!tz.equals(dtz.getID())) {
				java.lang.System.err.println(tz + " does not equal " + dtz.getID());
			} else {
				java.lang.System.out.println(tz + " equals " + dtz.getID());
			}
		}
    }

My current workaround is to use the Java 8 TimeZone class.

**Comment by jodastephen** [comment]
The time-zone database uses aliases for some time-zones. Joda-Time normalizes the aliases to the canonical name for the zone.
