### ISSUE TITLE
UTCDateTimeZone class has package private access

### ISSUE THREAD

**Issue by smpawlowski** [JodaOrg/joda-time#225]
Hi!

We are using JodaTime in conjunction with SimpleXml for serialization. We cannot define a binding between object and converter in package other than org.joda.time. Would it be ok to make UTCDateTimeZone class public?

Best regards!
Slawomir

**Comment by jodastephen** [comment]
`UTCDateTimeZone` is a private implementation class. All references to it should be via `DateTimeZone`. Private implementation classes of public interfaces/classes are a common design pattern in Java, so I'm sure SimpleXml has a solution for it.
