### ISSUE TITLE
DateTimeFormat.forPattern("yyyyww") not working properly

### ISSUE THREAD

**Issue by andreaskuehne** [JodaOrg/joda-time#226]
Hi,

I have some troubles with parsing a specific format to a date. When I want to parse "201401" with the given format 'yyyyww', I'd expect the library to return the first week of the year 2014. I tried with several other years and weeks which all seem to work fine, but in this special case it returns the 29th of december 2014, which is not correct. Native Java (DateFormat) works as expected.

Here is the example to reproduce:

public class Test {

	public static void main(String args[]) throws ParseException {

		DateTimeFormatter dtfOut = DateTimeFormat.forPattern("yyyyww");
		System.out.println("Formatted with Joda: \t\t" + dtfOut.parseDateTime("201401").toString());

		DateFormat dfmt = new SimpleDateFormat("yyyyww");
		System.out.println("Formatted with native Java: \t" + dfmt.parse("201401").toString());

	}

}

Output:

Formatted with Joda: 		2014-12-29T00:00:00.000+01:00	-> not correct
Formatted with native Java: 	Mon Dec 30 00:00:00 CET 2013	-> correct

I'm using the latest version of Joda (2.7)

**Comment by jodastephen** [comment]
When using week-of-weekyear (the "w" pattern letter) you should use the weekyear pattern letter "x" (not the year "y"). See the [format letters](http://www.joda.org/joda-time/key_format.html).

**Comment by andreaskuehne** [comment]
thanks
