### ISSUE TITLE
Incorrect month-wrapping behavior in MonthDay.plusDays

### ISSUE THREAD

**Issue by dancavallaro** [JodaOrg/joda-time#227]
`MonthDay.plusDays` does not return the expected value when adding a number of days that would cause the month to rollover more than once. The following (failing) test case shows the bug:

```java
public void testMonthDayPlusDaysWrapsMonthCorrectly() {
    MonthDay d = new MonthDay(5,15);
    assertEquals(d.plusDays(25).plusDays(25), d.plusDays(50));
}
```

50 days after 5-15 should be 7-4, but `d.plusDays(50)` gives 6-4 instead. As far as I can tell, the bug is on this line: https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/field/BaseDateTimeField.java#L324. In this example, the problem is on the second iteration of that loop, when the month gets incremented again. It should be incremented from 6 to 7, but the increment is performed on the *original* month in the `instant` variable, rather than the current month (and `instant` is never updated). Do you agree that this is a bug? 

Additionally, I would like to propose an update to the `MonthDay.plusDays` Javadoc documentation that calls out that calculations that require wrapping past the end of February will be based on an assumption that February has 29 days, which will be incorrect in non-leap years. Calculations that require accuracy in this regard should use a type with a year field. For reference, the `MonthDay` class in the new Java 8 API calls this out in its documentation, and explicitly chose not to support date arithmetic for this very reason: http://docs.oracle.com/javase/8/docs/api/java/time/MonthDay.html.

If you're amenable to the doc update, I'll go ahead and send a pull request for my proposed change. If you agree the wrapping behavior is a bug, I'm happy to work on a patch (including test cases), but may need some guidance as the fix is not immediately obvious to me.

**Comment by dancavallaro** [comment]
On the other hand, `YearMonthDay.plusDays` does not exhibit the same bug. This test passes as expected:

```java
public void testYearMonthDayPlusDaysWrapsMonthCorrectly() {
	YearMonthDay d = new YearMonthDay(2014,5,15);
	assertEquals(d.plusDays(25).plusDays(25), d.plusDays(50));
}
```

The difference, as far as I can tell, is that when adding days to a YearMonthDay and rolling over the month, we no longer enter [this block](https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/chrono/BasicMonthOfYearDateTimeField.java#L210-215) as we did when dealing with `MonthDay`, because month is no longer the largest field. Instead we enter [the next block](https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/chrono/BasicMonthOfYearDateTimeField.java#L216-223), where the original `ReadablePartial` actually gets modified for use in subsequent iterations of the algorithm loop.

**Comment by jodastephen** [comment]
Looks like a bug, although as you say, that logic gets complex. I'd generally go test first in a case like this, and see which exact examples fail.

A doc enhancement to plusDays() would also be welcome, as a separate PR if desired.

**Comment by dancavallaro** [comment]
PR for the doc update here: https://github.com/JodaOrg/joda-time/pull/229. Feel free to suggest wording changes, etc. 

I'll work on writing up some more test cases for the wrapping bug and we'll go from there.

**Comment by dancavallaro** [comment]
I added some test cases showing when the wrapping works, and when it doesn't, in both plusDays and minusDays: https://github.com/dancavallaro/joda-time/commit/a711195770ffdcd761d363fc61e74f48a66ef2c3

(see also my comment on that commit with the output of `mvn test`)

Couple quick questions about the tests:
* What does "int" mean in the test case names?
* Is there any reasoning behind the chronology chosen for the test? I notice that most of them either use ISOChronology or BuddhistChronology. I had to use ISOChronology for my tests because it seems the BuddhistChronology assumes all months to have 31 days.

**Comment by jodastephen** [comment]
"int" means that the method takes one int parameter. The chrono used was intended to be something other than ISO, to test edge cases, but its fine to test with ISO as well.

**Comment by dancavallaro** [comment]
Gotcha. Given that the intention of my new test cases is to test the behavior around wrapping at the end of the month, I think it's much clearer to use ISOChronology where the lengths of the months are what most people would expect (unless there's another chronology with similar behavior you suggest). 

Anyway, let me know if there are any other test cases you'd like to see, but I think those 8 illustrate the success and failure cases pretty well.

**Comment by jodastephen** [comment]
Fix made, excellent tests included ;-)

**Comment by dancavallaro** [comment]
Awesome, thanks a lot Stephen!
