### ISSUE TITLE
PeriodFormat string resources are in ISO 8859-1 encoding instead of UTF-8

### ISSUE THREAD

**Issue by elFua** [JodaOrg/joda-time#228]
migrated from _https://github.com/dlew/joda-time-android_ since the problem is in the upstream code

### Description
The resource bundle strings for PeriodFormat (and possibly others) are using ISO Latin-1 encoding instead of UTF-8.

For example this file is not UTF-8 encoded (actual encoding is ISO 8859-1):

https://github.com/dlew/joda-time-android/blob/master/library/src/org/joda/time/format/messages_es.properties.

NOTE: *github shows it without problems because it detects it correctly as _ISO-8859-1_*.

These files have incorrect encoding:

    messages_es.properties
    messages_fr.properties
    messages_da.properties
    messages_pt.properties

### Actual result
Strings render in android apps with broken accented characters.

### Expected result
Accented characters are displayed correctly.

### Suggested solution
Re-encode the `.properties` files to UTF-8 or to Unicode escapes.

Example using `iconv`:

    iconv -f ISO-8859-1 -t UTF-8 messages_es.properties > messages_es_UTF8.properties

**Comment by jodastephen** [comment]
The Java `Properties` class specifies that a stream is loaded using ISO 8859-1, so this is perhaps an Android bug.

However, I'd be happy to accept a PR that used `Properties.load(Reader)` and specified the encoding. What is needed is that the file and loading agree on the charset. Whether thats UTF-8 or not is slightly separate (although probably a good idea).

**Comment by jodastephen** [comment]
Encoded using unicode escapes
