### ISSUE TITLE
Incorrect SBT dependency info for SBT

### ISSUE THREAD

**Issue by jrmcauliffe** [JodaOrg/joda-time#230]
The dependency info for SBT is incorrect

libraryDependencies += "joda-time" %% "joda-time" % "2.7"

should be

libraryDependencies += "joda-time" % "joda-time" % "2.7"

I couldn't find it in the site code, not sure how you're generating it.

cheers,

Jon

**Comment by jodastephen** [comment]
[Bug was in maven](http://jira.codehaus.org/browse/MPIR-296), now fixed. So, I've regenerated the site.
