### ISSUE TITLE
DateTime.withDate problem on specific days

### ISSUE THREAD

**Issue by jcedric** [JodaOrg/joda-time#233]
When we call withDate on a DateTime it can happen that the received DateTime has a wrong time.

For instance
```java
DateTime date1 = new DateTime(2015, 1, 28, 2, 55, 0, 0).withZoneRetainFields(DateTimeZone.forID("Europe/Zurich"));
System.out.println(date1.withDate(2010, 3, 10) + " - " + date1.getZone());
DateTime date2 = new DateTime(2015, 1, 30, 2, 55, 0, 0).withZoneRetainFields(DateTimeZone.forID("Europe/Zurich"));
System.out.println(date2.withDate(2010, 3, 10) + " - " + date1.getZone());
```

Will print :
2010-03-10T03:55:00.000+01:00
2010-03-10T02:55:00.000+01:00

The first one is wrong. 
This is because on the 03-28-2010 02:00:00 there was time change and the implementation of withDate will change first the year, then the month, then the day. The problem occured when the month is changed.

**Comment by jodastephen** [comment]
Thanks for the report.

**Comment by jcedric** [comment]
Thanks for the quick fix
