### ISSUE TITLE
parsing ISO 8601 defect?

### ISSUE THREAD

**Issue by sbartram** [JodaOrg/joda-time#235]
Using the DateTimeFormatterBuilder.appendTimeZoneOffset method, I can create valid ISO8601 strings like this: "2004-03-15T12:34:56.789Z".   However, I can't get any strings containing the "Z" character to be parsed.  Is this a known issue? Does it only support the "+/-hhmm" syntax?

**Comment by jodastephen** [comment]
Please supply a test case that you think should pass.

**Comment by sbartram** [comment]
Sorry, it appears that the code in question was using a very old version of joda-time.  The current version is working.

Thanks
