### ISSUE TITLE
Period: parse does not always handle negative milliseconds field

### ISSUE THREAD

**Issue by jonsmock** [JodaOrg/joda-time#238]
I assume the intent is that `toString` and `parse` would roundtrip, but I could be wrong. Also, from what I can tell, having `Period`s with negative fields is permitted. Both are true of `Duration`. Let me know if either are not supported for `Period`.

Here's an example:

```
Period pExpected = Period.new(0, 0, 0, -1); // negative 1 millisecond
String correctString = pExpected.toString(); // "PT-0.001S"
Period pActual = Period.parse(correctString); // positive 1 millisecond
```

Hopefully that works. I'm using joda-time from Clojure, so I don't have a proper Java environment setup. I wanted to check with you before I tried to get the tests running, etc., and attempt a fix.

In case it helps, here is my original Clojure test, from which this was extracted:

```
(let [p (org.joda.time.Period. 0 0 0 -1)]
  (= p
     (org.joda.time.Period/parse (.toString p)))) ; => returns false
```

**Comment by jonsmock** [comment]
I'm realizing now that `Duration.parse` doesn't use the PeriodFormatter machinery and explicitly says it parses the output from its `toString`:

http://joda-time.sourceforge.net/apidocs/org/joda/time/Duration.html#parse(java.lang.String)

Also just found this: http://stackoverflow.com/questions/6387723/displaying-negative-time-periods-with-joda-time-periodformatter

I see that adding the rejectSignedValues does trigger a parse error, which is nice (sorry Clojure again):
```
  ; copied entirely from (org.joda.time.format.ISOPeriodFormat/standard)
  (let [formatter (-> (org.joda.time.format.PeriodFormatterBuilder.)
                      (.appendLiteral "P")
                      (.appendYears)
                      (.appendSuffix "Y")
                      (.appendMonths)
                      (.appendSuffix "M")
                      (.appendWeeks)
                      (.appendSuffix "W")
                      (.appendDays)
                      (.appendSuffix "D")
                      (.appendSeparatorIfFieldsAfter "T")
                      (.appendHours)
                      (.appendSuffix "H")
                      (.appendMinutes)
                      (.appendSuffix "M")
                      (.rejectSignedValues true) ; Only difference from ISOPeriodFormat/standard
                      (.appendSecondsWithOptionalMillis)
                      (.appendSuffix "S")
                      (.toFormatter))
        p   (org.joda.time.Period. 0 0 0 -1)
        s   (.print formatter p)] ; => "PT-0.001S"
    (.parsePeriod formatter s))
```

I'm having a little trouble following the FieldFormatter code. It appears '-' is supported:

https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/format/PeriodFormatterBuilder.java#L1589-L1594

Is it that "1" is passed to parseInt instead of "-1"?

**Comment by jonsmock** [comment]
Apologies, I just realized this is only a problem with milliseconds:

```
(let [p (org.joda.time.Period. 0 0 0 -1)]
  (= p
     (org.joda.time.Period/parse (.toString p)))) ; => returns false

(let [p (org.joda.time.Period. -1 0 0 0)]
  (= p
     (org.joda.time.Period/parse (.toString p)))) ; => returns true

(let [p (org.joda.time.Period. -1 0 0 -1)]
  (org.joda.time.Period/parse (.toString p))) ; => returns Period with -1 hrs, +1 ms
```

**Comment by jonsmock** [comment]
I'm realizing now, it's related to the fact that milliseconds are tied to seconds. A period with -1 seconds and -1 milliseconds roundtrips as well. A period with -1 seconds and +1 milliseconds serializes to -999ms and then parses as +999ms.

It looks like a problem in FieldFormatter:

https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/format/PeriodFormatterBuilder.java#L1656-L1658

When seconds are 0, the wholeValue is 0, so we do not negate the milliseconds portion properly. I honestly missed this when I first read that, and I only saw it when I played with the examples here.

**Comment by jonsmock** [comment]
Like I said, I haven't setup the environment to run the tests, etc.  This is just an idea:

https://github.com/jonsmock/joda-time/commit/5e3b122b078164c19af8a0b7d44e7a0a17d27ac2

If you like it, take it. Or, if you want me to actually add tests, make the change, and submit a real pull request, I can do that.

Thanks for listening!

**Comment by jodastephen** [comment]
Fixed, thanks

**Comment by jonsmock** [comment]
Thank you!
