### ISSUE TITLE
24h time format parsing bug

### ISSUE THREAD

**Issue by blipinsk** [JodaOrg/joda-time#240]
Format parser assumes wrong value bounds for 24h time format.
Currently bounds are being set to `[1,24]` and should be `[0,23]`.

For example, using pattern `"yyyy-MM-dd kk:mm:ss"` for parsing `2014-04-25 00:57:55` will result in error:

    org.joda.time.IllegalFieldValueException: Cannot parse "2014-04-25 00:57:55": Value 0 for clockhourOfDay must be in the range [1,24]

(`00:57:55` is a proper time format for 57 minutes past midnight)

(just to be clear - testing version 2.7)

**Comment by blipinsk** [comment]
just to be clear - testing on version 2.7

**Comment by jodastephen** [comment]
As per the [docs](http://www.joda.org/joda-time/key_format.html), the letter "k" is for hour-of-day from 1 to 24. For 0 to 23, you need to use pattern letter "H".
