### ISSUE TITLE
Prevent proguard warnings with no-tzdb version

### ISSUE THREAD

**Issue by dlew** [JodaOrg/joda-time#246]
People are getting warnings from proguard because not all linked classes are included - in particular, `DateTimeZoneBuilder` is included in the JAR, but not `ZoneInfoCompiler`, so it throws a fit (even though neither are actually used).

I'm not sure what needs to be removed - probably just `DateTimeZoneBuilder`. Either that, or just include all the source in no-tzdb.

**Comment by jodastephen** [comment]
Please try the snapshot build to confirm if this solves the issue.

**Comment by dlew** [comment]
Sorry for the slow response - I can confirm this fixes the proguard issue.

There are other proguard warnings that come up, but nothing that could be fixed here - in particular, the reference to `javax.xml.bind.DatatypeConverter` in joda-convert since that doesn't exist on Android. But I don't think that's even used in joda-time proper, so we can just tell proguard to ignore that warning.
