### ISSUE TITLE
Would it be feasible/advantageous to have non-final versions of some of the "final" classes?

### ISSUE THREAD

**Issue by RenniePet** [JodaOrg/joda-time#247]
Please take a look here:
http://stackoverflow.com/questions/28902892/is-it-somehow-possible-to-extend-joda-time-classes-marked-final

Specifically:

"Would the following solution be viable? Could we have a structure where, for example, LocalDate is derived from LocalDateNonFinal? LocalDate is an empty class that is marked "final". All functionality is in LocalDateNonFinal.

So if you really want to extend the LocalDate class, and only intend to use the extended class in your own programs, then you can instead extend LocalDateNonFinal, and call it MyLocalDate. This will not expose other modules to possible mistakes on your part because they will still require LocalDate, and won't accept LocalDateNonFinal or your MyLocalDate."

Disclaimer: My knowledge of Java and Joda-Time is very limited, so feel free to tell me that this is a dumb idea.  :-)

**Comment by jodastephen** [comment]
Joda-Time already has [lots of abstract superclasses](http://www.joda.org/joda-time/apidocs/org/joda/time/base/package-summary.html). I don't think any more are needed, as they increase the API for limited benefit.
