### ISSUE TITLE
Fraction of Second Parsing adds an additional zero in case fraction is empty

### ISSUE THREAD

**Issue by selmantayyar** [JodaOrg/joda-time#256]
Hello,

I am trying to parse the following date with Joda time:"2007-12-14T12:34:56"
I need to parse also fraction of second parts in case i have a date like "2007-12-14T12:34:56.789Z"

However,in the first case my formatter adds ".0" to the given date.Code is available below.It outputs
"2007-12-14T12:34:56.0"  instead of "2007-12-14T12:34:56"

Thanks in advance for your help.

P.S:I am using version 2.7

	public static void main(String[] args) {
	
		
		 DateTimeFormatter FRACTION_OF_SECOND_WITH_DOT_LITERAL_FORMATTER=new DateTimeFormatterBuilder()
     	.appendLiteral('.')
     	.appendFractionOfSecond(1, 3)
     	.toFormatter();
		 
		DateTimeParser [] parsers =new DateTimeParser[]{FRACTION_OF_SECOND_WITH_DOT_LITERAL_FORMATTER.getParser(),null};

		DateTimeFormatter localDateHMSFormatter = new DateTimeFormatterBuilder()
		.append(ISODateTimeFormat.dateHourMinuteSecond()).toFormatter();

		DateTimeFormatter finalFormatter=new DateTimeFormatterBuilder()
		.append(localDateHMSFormatter)
		.append(FRACTION_OF_SECOND_WITH_DOT_LITERAL_FORMATTER.getPrinter(), parsers)
		.toFormatter();
		
		DateTime dateTime = finalFormatter.parseDateTime("2007-12-14T12:34:56");
		String result = finalFormatter.print(dateTime);
		System.out.println(result);

	}

**Comment by jodastephen** [comment]
This produces a formatter that can parse both with and without milliseconds, but only prints down to the second level. I don't know if that is what you want, but in general you can combine formatters to produce almost any result. In addition , you can implement `DateTimePrinter` and `DateTimeParser` yourself and integrate them.

```
DateTimeFormatter finalFormatter = new DateTimeFormatterBuilder()
    .append(ISODateTimeFormat.dateHourMinuteSecond().getPrinter(),
        new DateTimeFormatterBuilder()
            .append(ISODateTimeFormat.dateHourMinuteSecond())
            .append(null, parsers).toParser())
    .toFormatter();
```

**Comment by selmantayyar** [comment]
Thanks Stephen.This is not exactly what i wanted,however i found a workaround it.
Cheers!
