### ISSUE TITLE
org.joda.time.IllegalInstantException: Cannot parse "2015-03-22"

### ISSUE THREAD

**Issue by MohsenK** [JodaOrg/joda-time#258]
Hi
I recently get this exception with Time Zone Asia/Tehran.

org.joda.time.IllegalInstantException: Cannot parse "2015-03-22": Illegal instant due to time zone offset transition (Asia/Tehran)

What is the problem ?
Thanks.

**Comment by jodastephen** [comment]
See the [FAQ](http://www.joda.org/joda-time/faq.html#illegalinstant)
