### ISSUE TITLE
Converting from C# DateTime to JodaTime DateTime through Jersey

### ISSUE THREAD

**Issue by xzuttz** [JodaOrg/joda-time#260]
I created a webservice using Tomcat and Jersey. The webservice consumes the following DTO class:

    import org.joda.time.DateTime;

    public class SurveyDTO {
	 private DateTime startDate;
	 private DateTime endDate;
	 private String numberOfPeople;
	 
	public DateTime getStartDate() {
		return startDate;
	}
	public void setStartDate(DateTime startDate) {
		this.startDate = startDate;
	}
	public DateTime getEndDate() {
		return endDate;
	}
	public void setEndDate(DateTime endDate) {
		this.endDate = endDate;
	}
	public String getNumberOfPeople() {
		return numberOfPeople;
	}
	public void setNumberOfPeople(String numberOfPeople) {
		this.numberOfPeople = numberOfPeople;
	}
    }

When sending a C#  object to the webservice with the following strcutre:

    public class Survey {
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
        public String numberOfPeople { get; set; }
    }

I get the following error:

"Can not instantiate value of type [simple type, class org.joda.time.DateTime] from String value; no single-String constructor/factory method (through reference chain: prediction.businesslogic.entity.DTO.SurveyDTO[\"startDate\"])"

If I use the java.util.Date instead of JodaTimes DateTime, the conversion works fine.

JodaTime is probably not suposed to be able to handle this scenario, but it would be nice if it could.

Best regards.

**Comment by jodastephen** [comment]
Most Java frameworks require a plugin of some kind to work with Joda-Time. The `java.util.Date` class works because it is built into Java.

On Java 8, the `java.time` API is built in, so tools like this are likely to work with those classes going forwards.
