### ISSUE TITLE
JodaTime contructor gives different results for very old dates (< 1891-10-02)

### ISSUE THREAD

**Issue by rsebestik** [JodaOrg/joda-time#264]
Hello.

For dates older then 1891-10-02 the results are different for:
a) LocalDate.fromCalendarFields(Calendar) and LocalDate.fromDateFields(Date)
b) new LocalDate(long) and new LocalDate(Date)

Difference starts at 2nd October 1891 and is increasing while going to the past.

LocalDate.fromDateFields(Date) and new LocalDate(Date) should imho return the same LocalDate.

Possible connection with timeZone sensitiveness java.util.Date https://github.com/JodaOrg/joda-time/issues/91

Reproduction:
```
 	public static void main(String[] args) {
		System.out.println(LocalDate.class.getPackage().getImplementationVersion());
		testDate(new GregorianCalendar(2015, 0, 2));
		testDate(new GregorianCalendar(1891, 9, 2));
		testDate(new GregorianCalendar(1891, 9, 1));
		testDate(new GregorianCalendar(1, 0, 2));
	}

	private static void testDate(Calendar cal) {
		System.out.print("fromCal: " + LocalDate.fromCalendarFields(cal));
		System.out.print(" fromDate: " + LocalDate.fromDateFields(cal.getTime()));
		System.out.print(" constr. date: " + new LocalDate(cal.getTimeInMillis()));
		System.out.print(" constr. millis: " + new LocalDate(cal.getTime()));
		// System.out.print(" GJCH constr. " + new LocalDate(cal.getTimeInMillis(), GJChronology.getInstance()));


		System.out.print(" -- ");

		long jodaDateMs = new LocalDate(cal.getTimeInMillis()).toDate().getTime();
		long dateMs = new Date(cal.getTimeInMillis()).getTime();
		//      System.out.print(" JODA from millis: "+jodaDateMs);
		//      System.out.print(" Date from millis: "+dateMs);
		System.out.print(" Diff in hours: "+(jodaDateMs-dateMs)/1000/60/60);
		System.out.println();
	}
```

Output:
> 2.7
fromCal: 2015-01-02 fromDate: 2015-01-02 constr. date: 2015-01-02 constr. millis: 2015-01-02 --  Diff in hours: 0
fromCal: 1891-10-02 fromDate: 1891-10-02 constr. date: 1891-10-02 constr. millis: 1891-10-02 --  Diff in hours: 0
fromCal: 1891-10-01 fromDate: 1891-10-01 constr. date: 1891-09-30 constr. millis: 1891-09-30 --  Diff in hours: -24
fromCal: 0001-01-02 fromDate: 0001-01-02 constr. date: 0000-12-30 constr. millis: 0000-12-30 --  Diff in hours: -72

**Comment by jodastephen** [comment]
This is an intended difference.

The constructor uses the same instant in time, whereas the `from*Fields` method tries to lo retain the same meaning even if it relates to a different instant.

The root cause is that the time-zone data differs between Joda-Time and the JDK, notably for older dates.
