### ISSUE TITLE
Add static DateTime.of() instance creation method like JodaMoney has

### ISSUE THREAD

**Issue by simon-templar** [JodaOrg/joda-time#265]
First off I don't know how to mark this as a discussion, but that's the intention of this issue.

As the title says I'd like there to be static creation methods for DateTimes.
I primarily like them because it eliminates some code clutter, the 'new' keyword.

On a slightly different point, I'm not sure "of" is a great name. In an effort again to reduce the amount of code noise I mostly add a static import for the methods in question, so Money.of(...) would become simply of(...) which isn't very descriptive.

So I guess I would like, I'm wincing a bit writing this, but Money.money(...), so in my static import world a declaration could look like:
Money wages = money(Currency.GBP, 1000000);

And therefore getting back to this library:
DateTime christmas = dateTime(2015, 12, 25, 0, 0);

What do people think?

**Comment by simon-templar** [comment]
First off I don't know how to mark this as a discussion, but that's the intention of this issue.

As the title says I'd like there to be static creation methods for DateTimes.
I primarily like them because it eliminates some code clutter, the 'new' keyword.

On a slightly different point, I'm not sure "of" is a great name. In an effort again to reduce the amount of code noise I mostly add a static import for the methods in question, so Money.of(...) would become simply of(...) which isn't very descriptive.

So I guess I would like, I'm wincing a bit writing this, but Money.money(...), so in my static import world a declaration could look like:
Money wages = money(Currency.GBP, 1000000);

And therefore getting back to this library:
DateTime christmas = dateTime(2015, 12, 25, 0, 0);

What do people think?

**Comment by jodastephen** [comment]
Joda-Time has some factory methods, but has long used constructors as the main entry point. JSR-310 in Java 8 uses factory methods exclusively. Changing Joda-Time to factory methods from constructors seems relatively low value at this point (usage of Joda-Time is likely to decline over time as users adopt Java 8).

My recommendation for static imports is to write a standalone utility class that has all the factory methods desired. It could potentially include money and time in the same class. Teaching the IDE to static import from one big class is easy. Thus it would be `DateTimes.date(2015, 3, 14)`, which would statically import to `date(2015, 3, 14)`

**Comment by simon-templar** [comment]
I think I will do just what you describe, as it's going to be some time before we can start using Java 8.
I really appreciate you taking the time to leave this feedback, thanks.
