### ISSUE TITLE
Bug in addSeconds()?

### ISSUE THREAD

**Issue by bojlxb** [JodaOrg/joda-time#266]
**Code:**
```
import java.text.SimpleDateFormat;
import java.util.Calendar;

import org.joda.time.DateTime.Property;
import org.joda.time.DateTimeZone;
import org.joda.time.MutableDateTime;


public class joda_datetime2 {

	public static void main(String[] args) {
		long time = 1174788000000L;
		int interval = -49680;
		SimpleDateFormat sdt = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
		
		/* CALENDAR */
		Calendar c = Calendar.getInstance();
		c.setTimeInMillis(time);
		System.out.println("CALENDAR1: " + sdt.format(c.getTime()) + " - " + c.getTimeZone());
		c.set(Calendar.SECOND, c.get(Calendar.SECOND)+interval);
		System.out.println("CALENDAR2: " + sdt.format(c.getTime()) + " - " + c.getTimeZone());
		
		/* JODA */
		MutableDateTime mdt = new MutableDateTime(time);
		System.out.println("____JODA1: " + sdt.format(mdt.toDate()) + " - " + mdt.getZone().toTimeZone());
		mdt.addSeconds(interval);
		System.out.println("____JODA2: " + sdt.format(mdt.toDate()) + " - " + mdt.getZone().toTimeZone());
	}

}
```

**Results:**

> CALENDAR1: 2007-03-25T09:00:00.000+07:00 - sun.util.calendar.ZoneInfo[id="Asia/Novosibirsk",offset=21600000,dstSavings=0,useDaylight=false,transitions=68,lastRule=null]
> CALENDAR2: 2007-03-24T**19**:12:00.000+06:00 - sun.util.calendar.ZoneInfo[id="Asia/Novosibirsk",offset=21600000,dstSavings=0,useDaylight=false,transitions=68,lastRule=null]
> ____JODA1: 2007-03-25T09:00:00.000+07:00 - sun.util.calendar.ZoneInfo[id="Asia/Novosibirsk",offset=21600000,dstSavings=0,useDaylight=false,transitions=68,lastRule=null]
> ____JODA2: 2007-03-24T**18**:12:00.000+06:00 - sun.util.calendar.ZoneInfo[id="Asia/Novosibirsk",offset=21600000,dstSavings=0,useDaylight=false,transitions=68,lastRule=null]

**Comment by jodastephen** [comment]
Comparing JDK calendar and Joda-Time is difficult. In this case, simply print out the difference in the millisecond timestamp before and after:

        long startInstant1 = time / 1000L;
        long endInstant1 = c.getTimeInMillis() / 1000L;
        System.out.println(endInstant1 - startInstant1);

and you will get `-46080`, which is 3600 seconds less than the subtraction requested.

Joda-Time has subtracted -49680 seconds as requested. The JDK subtracted -49680 seconds from the *local* time-line and then adjusted the millisecond instant to match, which results in an hour difference thanks to DST.
