### ISSUE TITLE
the LocalDateTime constructor with a LocalDate argument throws a runtime exception

### ISSUE THREAD

**Issue by mi9rom** [JodaOrg/joda-time#267]
example:  LocalDateTime tst = new LocalDateTime(LocalDate.now());
You get a runtime exception.
Logical behaviour should be to construct a LocalDateTime object with the time part set to the beginning of a day or for safety reasons it shouldn't throw an unchecked exception.

**Comment by jodastephen** [comment]
Joda-Time constructors have avoided adding information out of thin air, which is what would be needed here. It is easy to combine a `LocalDate` and a `LocalTime` using `LocalDate.toLocalDateTime(LocalTime)`.
