### ISSUE TITLE
Redundant check

### ISSUE THREAD

**Issue by bugsend** [JodaOrg/joda-time#271]
Hi! I've been struggling with my own issue using jada-time project and found a redundant check ( imho ) in file <b>DateTimeFormatterBuilder.java<b> in method public int parseInto(DateTimeParserBucket bucket, CharSequence text, int position).

There is a check for two strings equality, first based on <b>toUpperCase</b> string transformation and if we had no luck, then <b>toLowwerCase</b> transformation, which is unnecessary since if first check gonna fail than the second one wont  success either...

**Comment by jodastephen** [comment]
Suggest you do some googling on [case sensitive comparison in Turkish](http://blog.codinghorror.com/whats-wrong-with-turkey/).

**Comment by bugsend** [comment]
Have you looked at equalsIgnoreCase ? Looks like far more conscious.

Btw, seems like test cases for mentioned class must be adjusted to fail in case you tried to protect from. Right now they all pass successfully after eliminating the lower case check.
