### ISSUE TITLE
Chilean timezone offset is wrong

### ISSUE THREAD

**Issue by caente** [JodaOrg/joda-time#272]
It seems like the offset for chile is off, it should be `-03:00`
It is `-03:00` everywhere, but joda-time :-/
```
@ val now = DateTime.now(DateTimeZone.UTC)
now: org.joda.time.DateTime = 2015-05-05T17:32:45.830Z
@ val tz = DateTimeZone.forID("America/Santiago")
tz: org.joda.time.DateTimeZone = America/Santiago
@ now.withZone(tz)
res17: org.joda.time.DateTime = 2015-05-05T13:32:45.830-04:00
```

**Comment by jodastephen** [comment]
Updated to TZDB 2015d

**Comment by wheelertom** [comment]
Using 2.9.1, and JVM 1.7.0_80
Having problems with `TimeZone` -- `America/Santiago`
Should be `-03:00`, right?
```
String time = "2016-04-27T14:32:36.345";
TimeZone tz = TimeZone.getTimeZone("America/Santiago");
DateTimeFormatter fmt = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS")
        .withZone(DateTimeZone.forTimeZone(tz));
DateTime formattedDate = fmt.parseDateTime(time);
System.out.println(formattedDate);

$ 2016-04-27T14:32:36.345-04:00
```

However, `String time = "2016-10-27T14:32:36.345"` -- produces: `2016-10-27T14:32:36.345-03:00`.

**Comment by jodastephen** [comment]
The input gives me -03:00. You probably have an old version of Joda-Time lurking on your classpath,

**Comment by wheelertom** [comment]
ok... great.  I'll have a look.  Thanks.

**Comment by wheelertom** [comment]
yup... that was it. :\

**Comment by AndrewGnagy** [comment]
I believe this is wrong again as of 2016 when Chile re-implemented winter time https://www.worldtimeserver.com/news/chile-to-switch-back-to-standard-time/
Is it preferable to re-open this ticket or create a new one?
