### ISSUE TITLE
ISODateTimeFormat.dateTimeParser() does not parse timezone

### ISSUE THREAD

**Issue by bunkenburg** [JodaOrg/joda-time#277]
If I understand the documentation correctly, ISODateTimeFormat.dateTimeParser() parses an optional timezone. So in this code:

		DateTimeFormatter parser=ISODateTimeFormat.dateTimeParser();
		DateTime dt=parser.parseDateTime("2015-05-08T14:43:00+00:00");
		Date d=dt.toDate();
		int offset=d.getTimezoneOffset();

I'd expect offset to be 0, but it comes out -120, which is my timezone.

**Comment by jodastephen** [comment]
Use `ISODateTimeFormat.dateTimeParser().withOffsetParsed()`

**Comment by bunkenburg** [comment]
Ok, thanks! Maybe the doc comment of the method could make that more obvious.
