### ISSUE TITLE
Threading issue with org/joda/time/tz/CachedDateTimeZone.java

### ISSUE THREAD

**Issue by sshrdp** [JodaOrg/joda-time#278]
Using an array for caching is not thread safe:
private final transient Info[] iInfoCache = new Info[cInfoCacheMask + 1];

The reason is that putting an object in an array is not a write barrier. 
Is it possible to replace it with a thread-safe cache?

**Comment by jodastephen** [comment]
Have you seen any actual issues from this?

**Comment by sshrdp** [comment]
It's hard to say if it's causing an issue. However I can change it to an AtomicReferenceArray if there are no objections.

**Comment by jodastephen** [comment]
The problem is that an atomic array would undoubtedly be slower. Without evidence to suggest there is a problem it is tricky to justify that. In addition, I have a memory of asking about this before of the top JVM experts and them indicating that it wasn't a problem.

**Comment by sshrdp** [comment]
Oh, this one is safe. All the Info fields are final except iNextInfo (which is reference to Info), two int fields that are lazily initialized and iNameKey which references an String that's also immutable.
