### ISSUE TITLE
Failed to invoke public org.joda.time.Chronology() with no args

### ISSUE THREAD

**Issue by IlyaMyasoedov** [JodaOrg/joda-time#294]
I can not write properly objects with joda time classes into json. 
Here  a piece of code for writing the object to json
<pre><code class='haxe'>
Gson gson = new GsonBuilder().serializeNulls().create();
String json = gson .toJson(parseData);
</code>
</pre>
"parseData" is an object that contains not null classes of joda time. Then json string is sent to the server. After receiving this string from the server, i get the exception
<pre>java.lang.RuntimeException: Failed to invoke public org.joda.time.Chronology() with no args</pre>

in the place: 
<pre><code class='haxe'>
ParseData parseData = new Gson().fromJson(json, ParseData.class);
</code></pre>

**Comment by johnjaylward** [comment]
that's because Joda most objects are not beans. They are immutable objects that need proper values passed to a constructor, or need to be built with the builder methods:
i.e.
```java
DateTime dt = new DateTime(2015,06,12,0,0,0,0); // constructor
dt = dt.withSeconds(5); // builder methods start with "with"
```

Gson would need special handlers implemented to create the proper Joda objects. I'd suggest to file a bug with them

**Comment by johnjaylward** [comment]
or even look at this project: https://github.com/gkopff/gson-jodatime-serialisers

**Comment by IlyaMyasoedov** [comment]
Thanks for your answer. But unfortunately the project you said about isn't suitable for me. My ParseData class consists of several objects that contain joda Data and DateTime classes.

**Comment by IlyaMyasoedov** [comment]
Could you advise a good alternative to Google Gson serializer?

**Comment by johnjaylward** [comment]
I'm pretty sure you can do something like this with the linked project:
```java
final Gson gson = Converters.registerDateTime(new GsonBuilder()).create();
ParseData parseData = new Gson().fromJson(json, ParseData.class);
```

I think the example in the project is just very simple. Have you tried this, or something very similar?

**Comment by johnjaylward** [comment]
also, in case you didn't notice, you can chain the converters, although I must say the syntax is ugly:
```java
final Gson gson = Converters.registerDateMidnight(Converters.registerLocalTime(Converters.registerDateTime(new GsonBuilder())));
```

**Comment by IlyaMyasoedov** [comment]
Thanks. You are right.

**Comment by SanielDous** [comment]
You could also just save the time millis in your custom objects and encapsulate it so that is works with Joda objects to the outside. For example:

    public class MyObject {
      private long date;

      public MyObject(DateTime date) {
          this.date = date.getMillis();
      }

      public DateTime getDate() {
          return new DateTime(date);
      }
    }
