### ISSUE TITLE
Provide a DateTimeFormatter.printTo() method for StringBuilder without checked exceptions

### ISSUE THREAD

**Issue by JanecekPetr** [JodaOrg/joda-time#298]
The `DateTimeFormatter` class now supports the handy `printTo()` method for appending a formatted date to an `Appendable` instance. However, the `append()` in `Appendable` throws an `IOException` which is very annoying to deal with when all I want to do is append a string to a `StringBuilder`.

Please, do what e.g. Guava did with their [`Joiner`](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/base/Joiner.html) and provide a specialized `printTo(StringBuilder builder, ReadableInstant instant)`

**Comment by jodastephen** [comment]
There is already a `printTo(StringBuffer, ...)` method, so adding this would be a little excessive.

**Comment by JanecekPetr** [comment]
I agree that having both `printTo(StringBuffer, ...)` and `printTo(StringBuilder, ...)` seems excessive. Unfortunately, the two classes don't have a good common interface (only `Appendable` which sucks), and `StringBuilder` is THE class to use nowadays, and `StringBuffer` usage is practically nonexistent.

Specifically for this method which should only be used for provably performance-sensitive cases, we were looking for the fastest way to output the correctly formatted date. Unfortunately, the current API is cumbersome :(.

If you think adding the method is too much, I get it, feel free to mark this is Won't Fix. The `StringBuffer`-compatible method was a step in the wrong direction, though, and `StringBuilder` would fix this. The API-baggage price is high, though, of course.

**Comment by jodastephen** [comment]
Three methods added to `DateTimeFormatter`.

Note that Joda-Time started before `Appendable` or `StringBuilder` existed, so `StringBuffer` was the correct choice back then.

**Comment by JanecekPetr** [comment]
Wow, I haven't ever realized that.
As always, you're the best, thank you!
