### ISSUE TITLE
Parsing dates with years < 1580

### ISSUE THREAD

**Issue by thv92** [JodaOrg/joda-time#301]
I am not sure if this has been discussed. I couldn't find it anywhere online, so I am asking here. I am currently parsing dates with years that are less than 1500 just for testing purposes and I came across a discrepancy in the output. As you can see below, The day is 10 days off. Is there something that I am not taking into consideration when parsing dates such as this?

Code:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`String date = "1581-05-27T10:34:56Z";`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`logger.info("Date: " + new Date(DateTime.parse(date).getMillis()));`
Output:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Date: Wed May 17 10:34:56 UTC 1581`

**Comment by sfyumi** [comment]
[From Julian to Gregorian | Wikipedia](https://en.wikipedia.org/wiki/Julian_calendar#From_Julian_to_Gregorian)

> The Julian calendar was in general use in Europe and Northern Africa until 1582, when Pope Gregory XIII promulgated the Gregorian calendar.  


> By 1582, it was ten days out of alignment from where it supposedly had been in 325 during the Council of Nicaea.

**Comment by jodastephen** [comment]
Using the `GJChronology` will get you closer.

    DateTimeFormatter formatter = ISODateTimeFormat
      .dateTimeParser()
      .withOffsetParsed()
      .withChronology(GJChronology.getInstance());

    DateTime parsed = DateTime.parse(date, formatter);
