### ISSUE TITLE
dependency issue 

### ISSUE THREAD

**Issue by Gupta126** [JodaOrg/joda-time#303]
dependencies {
   
    compile files('libs/httpmime-4.1.jar')
    compile project(':Aviary-SDK')
    compile 'com.google.android.gms:play-services-location:7.5.0'
    compile 'com.google.android.gms:play-services-maps:7.5.0'
    compile 'com.github.shell-software:fab:1.1.2'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'org.apache.commons:commons-compress:1.4.1'
    compile 'com.itextpdf.tool:xmlworker:5.5.6'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'net.danlew:android.joda:2.8.1'
   }

i am adding this line  compile 'net.danlew:android.joda:2.8.1' and it does not run produce error in IntelliJ IDEA Android Studio.

**Comment by JanecekPetr** [comment]
Hello.
(disclaimer: I'm not a Joda-Time developer, I was just checking up on my own reported issue and noticed yours)

* {{net.danlew:android.joda}} is not this library, you should go to https://github.com/dlew/joda-time-android. In here, the issue will most likely be closed.
* You didn't tell us what you're doing, and which error it produces. What does the error message say? Try trimming down your project until the error goes away. Try setting up a simple Hello World application that does nothing but outputs the current time and exits. Does that fail, too?
