### ISSUE TITLE
Timezone not setted correctly during convesion from java.sql.Timestamp to joda DateTime

### ISSUE THREAD

**Issue by rcardin** [JodaOrg/joda-time#306]
I am experimenting some stange issues while trying to convert an object of type `java.sql.Timestamp` into an object of time `org.joda.time.DateTime`. In detail, the Timezone seems to not be set correctly.

Here is my code (scala language):

    val receptionDate = 
      new DateTime(tuple("RECEPTION_TIMESTAMP").asInstanceOf[Timestamp].getTime(), 
                   DateTimeZone.UTC)

The `Timestamp` object is read directly from a database table (HBase) and the value showed by SQuirreL client is the following:

    2015-07-30 00:00:00.0

Instead, the `DateTime` object created has the value `2015-07-29 22:00:00.0`. Clearly during the creation of the `DateTime` object it is not used the information of the timezone `DateTimeZone.UTC`, that I am passing to the constructor.

What am I doing wrong? Where is the error?

I am using the `joda-time` library version 2.7.

Thanks a lot.

**Comment by alex31481** [comment]
The code is behaving as it should.

If you read the [Timestamp java doc](http://docs.oracle.com/javase/7/docs/api/java/sql/Timestamp.html) carefully you see that the time stamp object dose not contain timezone zone information. Therefore when you are creating the DateTime object the only information you are passing is UTC and the timestamp value. which means to recognize this time value as if it were in UTC per the documentation below.
```
DateTime(long instant, DateTimeZone zone) 
          Constructs an instance set to the milliseconds from 1970-01-01T00:00:00Z using ISOChronology in the specified time zone.
```
I am guessing your local time zone is  UTC-2 that and the code is doing whatever it was design to do. to solve your problem you have to do the following.

```
val zone = // figure out what is the zone the time stamp is was saved in.
val receptionDate = 
  new DateTime(tuple("RECEPTION_TIMESTAMP").asInstanceOf[Timestamp].getTime(), 
               zone)
```

**Comment by rcardin** [comment]
You were right. I've to force the same time zone (UTC) also when I produce the date that I will store into HBase as Timestamp.

Thanks a lot.
