### ISSUE TITLE
DateTime withTimeAtEndOfDay

### ISSUE THREAD

**Issue by maoueh** [JodaOrg/joda-time#308]
Hi,

Would you accept a PR adding `DateTime#withTimeAtEndOfDay` (and probably `LocalDate#toDateTimeAtEndOfDay` to support it)?

I'm often in a situation where I want to find some records by receiving a date (a `DateTime` instance) searching in my database between the start of day of this date (using `date.withTimeAtStartOfDay()`) and the end of day of this date (currently using `date.withTime(23, 59, 59, 999)`).

Having the opposite of `withTimeAtStartOfDay` would help readability of this kind of code.

Regards,
Matt

**Comment by jodastephen** [comment]
My feeling is that this is a step too far. The general advice is to use exclusive end bounds, avoiding the need for the 23:59:59.999 case.

**Comment by maoueh** [comment]
Hi @jodastephen,

Thanks for the follow-up. Could elaborate a little bit as I'm not sure I quite understand what you mean exactly. 

Are you suggesting to always use `withTimeAtStartOfDay` for both ends but for the ending date, use an exclusive bound when searching? That's seem an interesting point of view. I will explore this.

**Comment by maoueh** [comment]
When I said `use withTimeAtStartOfDay for both ends`, I meant one day later for ending bound of course.

**Comment by jodastephen** [comment]
Take a look at `Interval` and how it is implemented.

**Comment by andersonnathan** [comment]
I was looking for this as well, but I found another solution. I end up using .millisOfDay().withMaximumValue().  See example
```java
endDT = endDT.withYear(year).withMonthOfYear(month)
					.dayOfMonth().withMaximumValue()
					.millisOfDay().withMaximumValue();
```

**Comment by boncheo** [comment]
Use this
`DateTime.now().withTimeAtStartOfDay().minusSeconds(1).toDate()`

**Comment by bagrusss** [comment]
One more way
`dateTimeObj
            .withTimeAtStartOfDay()
            .minusMillis(1)
 `
