### ISSUE TITLE
Time Zone Wrong?

### ISSUE THREAD

**Issue by sunjunhqq** [JodaOrg/joda-time#310]
final MutableDateTime mdt2 = new MutableDateTime(2011, 10, 30, 2, 0, 0, 0, DateTimeZone.forID("Europe/Berlin"));
System.out.println("Start date:   " + mdt2 + " (" + mdt2.toInstant().getMillis() + ")");
final MutableDateTime mdt = new MutableDateTime(2011, 10, 30, 3, 0, 0, 0, DateTimeZone.forID("Europe/Berlin"));
System.out.println("Start date:   " + mdt + " (" + mdt.toInstant().getMillis() + ")");
mdt2.addHours(-1);
System.out.println("addHours(-1): " + mdt2 + " (" + mdt2.toInstant().getMillis() + ")");

The first output: Start date:   2011-10-30T02:00:00.000+02:00 (1319932800000)
The second output: Start date:   2011-10-30T03:00:00.000+01:00 (1319940000000)
The third output: addHours(-1): 2011-10-30T02:00:00.000+01:00 (1319936400000)

Apparently different zones. Is this supposed to be?

**Comment by jodastephen** [comment]
Nothing wrong here. You are querying instants around a daylight savings change. The last line outputs an instant that is 1 hour (60 minutes) earlier than the instant in the first line.
