### ISSUE TITLE
Period calculation inconsistent on months with different number of days

### ISSUE THREAD

**Issue by klyc0k** [JodaOrg/joda-time#314]
Not sure if this is a bug but looks like there's an inconsistency on calculating the period back and forth.

```
LocalDate date = new LocalDate(2015, 7, 31); // July 31st, 2015
Period period = new Period(0, 1, 0, 0, 0, 0, 0, 0); // 1 month
LocalDate minusDate = date.minus(period); // Got June 30th, 2015
Period calcPeriod = new Period(minusDate, date); // 1 month 1 day
```

**Comment by jodastephen** [comment]
This is a natural outcome of Joda-Time objects being immutable and holding no additional state.
July 31 minus 1 month cannot be June 31, so it is changed to June 30. But viewed the other way, it is obviously 1 month and 1 day.
