### ISSUE TITLE
'z' in the date formatter is sometimes behaving like 'Z'

### ISSUE THREAD

**Issue by mohamar** [JodaOrg/joda-time#316]
Hi I am using the date format 'forPattern("E MMM d HH:mm:ss z yyyy")' which should print me zone as 'CST' which it does sometimes . But more often it prints me 'America/Chicago' which it should print for 'Z'.
It would be a great help if someone has an answer for this . Thanks!

**Comment by devstuff** [comment]
If your code is running under Java 8u60 or later, you'll need JodaTime 2.8.1 or later (see https://github.com/JodaOrg/joda-time/commit/31ea144fd1fc493c2f2717d61b279c6caddae4db)

**Comment by jodastephen** [comment]
I don't really have enough information to investigate this.
