### ISSUE TITLE
Timezone offset is wrong

### ISSUE THREAD

**Issue by johanneslagos** [JodaOrg/joda-time#317]
Timezone offset for Norway is wrong. During the summer, until October, it should be CEST (+0200), but it is defined as CET (+0100). I imagine the problem also exist for other cities, Zurich, Stockholm, Madrid, Paris, etc.

**Comment by dlew** [comment]
You should start a thread on the tzdatabase about it: https://www.iana.org/time-zones

joda-time just pulls in the data provided by them.

**Comment by jodastephen** [comment]
Make sure you use the time zone "Europe/Oslo".
