### ISSUE TITLE
 Error in the validation. Validation code and error message do not match

### ISSUE THREAD

**Issue by jodastephen** [JodaOrg/joda-time#321]
Raised at dead [sourceforge](https://sourceforge.net/p/joda-time/bugs/178/) issue tracker.

Error in the validation. Validation code and error message do not match. It should be end <= start. org.joda.time.base.AbstractInterval.checkInterval():

    if (end < start) {
        throw new IllegalArgumentException("The end instant must be greater or equal to the start");
    }

**Comment by skokovsergey** [comment]
Hello, i made a mistake. It was correct condition and error message. Sorry!
