### ISSUE TITLE
Mistake in LocalDateTime construction

### ISSUE THREAD

**Issue by RasheR666** [JodaOrg/joda-time#322]
I've start use joda-time instead java.util.Date in my project. After this moment some test are failed.
In those tests i use date like 01.01.1900. It is a real example in real system.

I'm execute next code:
```java
java.util.Date date = new LocalDateTime(1900, 1, 1, 0, 0, 0, 0).toDate();
long timestamp = date.getTime();
java.util.Date newDate = new LocalDateTime(timestamp).toDate();
```

This two dates are not equals.

After this i start to search the moment when something goes wrong. I found this moment
```java
// When i execute 
new LocalDateTime(-1688270553000L); // it return me 02.07.1916 23:42:32
//But when i execute 
new LocalDateTime(-1688270554000L); // it return me 02.07.1916 23:59:59
```
I have changed only 1 second, but receive big difference. My timezone is GMT +5 (Yekaterinburg)

**Comment by jodastephen** [comment]
In 1916, the first time-zone was introduced there.

See http://www.timeanddate.com/time/zone/russia/yekaterinburg (selecting 1900-1924 in the drop down).
