### ISSUE TITLE
Really Freaky Formatter

### ISSUE THREAD

**Issue by landlockedsurfer** [JodaOrg/joda-time#324]
Hi!

I'm trying to find a way to parse a date string having the format

```
[YYYY][M]MDD
```

into a Joda LocalDate.

The `YYYY` section sets the number of years relative to the year 2000.
The `MM` section sets the month of the year, possible values are: 01,02,03,...12
The `DD` section sets the day of the month, possible values are: 01,02,03,...31

Trailing zeros can be omitted

Examples:
```
151028 => October 28, 2015
 11028 => October 28, 2001
  1028 => October 28, 2000
   128 => January 28, 2000
```

I've found the "Freaky Formatters" section in the docs:
http://www.joda.org/joda-time/userguide.html#Freaky_Formatters
but it looks like my use case requires a "Really Freaky Formatters" section. :-)

Has anybody a tip/example on how to parse the described date format following Joda Times best practices?

Thanks,
Manfred

**Comment by jodastephen** [comment]
You'd have to make the year optional and parse using [parseInto()](http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormatter.html#parseInto-org.joda.time.ReadWritableInstant-java.lang.String-int-) with a `MutableDateTime` set to year 2000.

**Comment by landlockedsurfer** [comment]
Thanks for your quick reply and your hint to the `parseInto()` function!
I came up with the following solution (using Scala):

```
  val formatter:DateTimeFormatter =
    new DateTimeFormatterBuilder()
      .appendOptional(new DateTimeParser {
        override def estimateParsedLength(): Int = 2
        override def parseInto(bucket: DateTimeParserBucket, text: String, position: Int): Int = {
          val l = text.length
          if(l < 3) {
            -1
          } else if(l<=4) {
            bucket.saveField(DateTimeFieldType.year(),2000)
            0
          }
          else {
            bucket.saveField(DateTimeFieldType.year(),2000 + text.substring(0,l-4).toInt)
            l-4
          }
        }
      })
      .appendOptional(new DateTimeParser {
        override def estimateParsedLength(): Int = 2
        override def parseInto(bucket: DateTimeParserBucket, text: String, position: Int): Int = {
          val l = text.length
          if(l < 2) {
            -1
          } else if(l==3) {
            bucket.saveField(DateTimeFieldType.monthOfYear(),text.substring(0,1).toInt)
            1
          }
          else {
            bucket.saveField(DateTimeFieldType.monthOfYear(),text.substring(l-4,l-2).toInt)
            l-2
          }
        }
      })
      .appendDayOfMonth(2)
      .toFormatter
``` 

The conversion function then looks like
```
def parseIpcDate(s:String):LocalDate = {
  LocalDate.parse(s,formatter)
}
```

I've also compared the performance of the DateTimeFormatter version against my custom parser and the runtimes are very similar.
