### ISSUE TITLE
Date difference in months for dates 

### ISSUE THREAD

**Issue by mvkk** [JodaOrg/joda-time#325]
I used the monthsBetween method to calculate months between dates and here is the summary of the outcomes:
1.'2013-03-31' and '2013-04-30' - Difference is 1
2. '2013-03-31' and '2014-02-28' - Difference is 11

While I get 0 for first and 10 for second set using SPSS, MySQL, Excel. 
Is there any way we can get monthsBetween match results?

**Comment by johnjaylward** [comment]
why would those tools (SPSS, MySQL, Excel) report 0 or 10... the difference to any sane person would be what Joda time is reporting.

**Comment by AdrianAcala** [comment]
Seems like he wants to round down.

**Comment by johnjaylward** [comment]
last day of the month to last day of the next month would be 1 month difference. I'm not seeing why you would expect a different result.

**Comment by mvkk** [comment]
I guess the last day is not included. Is there an option to include or not
include last day in the calculations?

**Comment by AdrianAcala** [comment]
According to [Microsoft](https://support.microsoft.com/en-us/kb/214134), the excel calculation is

    =IF(DAY(A1)>=DAY(B1),0,-1)+(YEAR(A1)-YEAR(B1)) *12+MONTH(A1)-MONTH(B1)

If you relate both examples to this excel code, it makes sense. May has not yet passed the 31st day of the month, which would only occur on June 1st, and therefore a month has not yet passed.

**Comment by AdrianAcala** [comment]
@mvkk, there's an issue I spotted when creating unit tests. The inverse does not make sense. For example, in your first example, 3/31/13 to 4/30/13 is suppose to have 0 months in between, but what would happen if you flipped the order so that you're looking for the months between 4/30/13 and 3/31/13. That would then be -1 months going backwards whereas 0 months going forward.

**Comment by mvkk** [comment]
That is true. The reverse does not make sense. My suggestion would be to
either have a validation that alerts the users about the wrong usage of
dates or just show the negative results as done by some of the databases.

**Comment by jodastephen** [comment]
Whether this is the right behaviour or not is slightly moot at this point. Joda-Time has worked this way for many years, so I'm not changing it.

**Comment by mvkk** [comment]
Hi Stephen,
I appreciate you letting me know of your decision.
I leave that you. I needed limited functionality to just count number of
days/months/years between two given dates.
And I have written custom functions to overcome the issues I had mentioned
in my previous emails.
Hence I am good for now.
However, if all major databases, MS Excel, statistical tools like SPSS,
STATA have implemented similar behaviour, you could think of doing the same
sometime in future.
All the best.

Regards
Kiran

**Comment by jodastephen** [comment]
Just to note that `java.time` in Java SE 8 does the following:

    System.out.println(Period.between(LocalDate.of(2013, 3, 31), LocalDate.of(2013, 4, 30)));
    P30D

    System.out.println(Period.between(LocalDate.of(2013, 3, 31), LocalDate.of(2014, 2, 28)));
    P10M28D

As stated above however, I won't be updating Joda-Time (which is primarily in maintenance mode).
