### ISSUE TITLE
DateTimeZone should load it's provider in an AccessController.doPrivileged block

### ISSUE THREAD

**Issue by s1monw** [JodaOrg/joda-time#327]
In elasticsearch we run into a testing issue where due to security manager restrictions the default providers could not be loaded. https://github.com/elastic/elasticsearch/issues/14524 The problem here is really that we can't grant the jar it's needed permissions since it doesn't use a `AccessController.doPrivileged block` to load the privider in
https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/DateTimeZone.java#L483 I am not sure if there are other places where stuff like this is loaded but there might be

**Comment by jodastephen** [comment]
Happy to accept a PR as you are in a better position to test this than me.

**Comment by jasontedor** [comment]
@jodastephen I'm with @s1monw at Elasticsearch. I opened #375 to address this issue so we can close out some user-reported bugs in Elasticsearch since we run under the security manager by default our current stable releases. Can we work together to get this integrated and have a version 2.9.4 released? :smile:

**Comment by jodastephen** [comment]
The spec for the getResourceAsStream() does not indicate security manager issues, but the JDK typically wraps the code like this, so it seems reasonable.

**Comment by jasontedor** [comment]
Thanks @jodastephen! Do you have a timeframe in mind for a patch release that contains #375 (and the additional code you added)?

**Comment by jodastephen** [comment]
Done

**Comment by jasontedor** [comment]
Thanks @jodastephen!
