### ISSUE TITLE
Date overflow in 2.9 when timezone offset crosses epoch

### ISSUE THREAD

**Issue by ThrawnCA** [JodaOrg/joda-time#328]
Starting from version 2.9, when I construct a DateTime in such a way that the timezone offset causes it to cross the epoch, the date overflows and jumps hundreds of millions of years ahead.

Sample code:

    import org.joda.time.DateTime;
    import org.joda.time.DateTimeZone;

    public class JodaCrossingEpoch {
        public static void main(String[] args) {
            // prints 1970-01-01T01:02:03.456+10:00 in 2.8.1,
            // but 292278994-08-17T17:12:55.807Z in 2.9
            System.out.println(new DateTime(1970, 1, 1, 1, 2, 3, 456, DateTimeZone.forOffsetHours(10)));
        }
    }

**Comment by jodastephen** [comment]
:sob:

**Comment by ThrawnCA** [comment]
That fixed it, thanks :).
