### ISSUE TITLE
parseDateTime accepts bad input

### ISSUE THREAD

**Issue by sparti** [JodaOrg/joda-time#329]
The following API calls both give a result, evenso the second date is not valid:

dateTimeCollectionFormatter = new DateTimeFormatterBuilder();
dateTimeCollectionFormatter.toFormatter().withZone(currentDateTimeZone).parseDateTime("Fri, 05 Jun 2015 02:00 am") 
dateTimeCollectionFormatter.toFormatter().withZone(currentDateTimeZone).parseDateTime("Sat, 05 Jun 2015 02:00 am") 

From the second date it is not clear which day is meant. It should not result in an error.

**Comment by jodastephen** [comment]
Joda-Time has always parsed this leniently with the result being undefined. As such, it would be backwards incompatible for this to change after 10 years of working this way.

**Comment by sparti** [comment]
Hmm, I didn't know that you can be compatible to an undefined behavior. Very strange decision... By the way NotABug is the wrong label, only WontFix applies.
