### ISSUE TITLE
Question: Joda Compatibility categorization

### ISSUE THREAD

**Issue by stokito** [JodaOrg/joda-time#330]
Hi,

Each [release of Joda](http://www.joda.org/joda-time/installation.html) contains six parts of compatibility :
* Build system
* Binary compatible
* Source compatible
* Serialization compatible
* Data compatible
* Semantic compatible

It looks for me a great categorization. But could you make more explanation about this categorization with examples.
I trying to collect all links about this https://stokito.wordpress.com/2015/11/13/compatibility/ so will be very thankful.

**Comment by jodastephen** [comment]
* Build system

Not part of compatibility, just a fact about the build system in use

* Binary compatible
* Source compatible

Whether the whole API is binary compatible or source compatible. See [this document](https://wiki.eclipse.org/Evolving_Java-based_APIs_2)

* Serialization compatible

Whether the serialization format is compatible with the previous version.

* Data compatible

Whether the data, time-zone data in this case, has changed.

* Semantic compatible

Whether there is some other semantic change. This is relevant when the classes and methods have not changed, but the meaning of a method has.

**Comment by stokito** [comment]
Thank you!
