### ISSUE TITLE
DateTime toDate() does not work according to timezone

### ISSUE THREAD

**Issue by kunalkhare** [JodaOrg/joda-time#331]
Hi,

Below is sample code which I tried to use to convert from CST time zone to EST:

    	DateTimeZone dtESTZone = DateTimeZone.forID("America/New_York");

        DateTimeFormatter formatter = DateTimeFormat.forPattern("dd-M-yyyy hh:mm:ss.S a").withZone(dtESTZone);

        DateTime jodatime = formatter.parseDateTime(date.toString()); 

My application server is in CST  timezone . So when I try jodatime.toDate() after above conversion it picks up JVM timezone as CST instead of converting it to EST timezone.

Thanks,
Kunal.

**Comment by jodastephen** [comment]
When you call `toDate()` on `DateTime`, you convert back to a `java.util.Date`. That class has no time-zone - it is just a wrapper around a `long` milliseconds value. However it does print out from `toString()` using the JVM default time-zone, which is probably what is confusing you..
