### ISSUE TITLE
Joda's DateTime is inconsistency with Calendar

### ISSUE THREAD

**Issue by zjffdu** [JodaOrg/joda-time#334]
The following code will get 2 different result which confuse me.  Is this a bug of Joda's DateTime.
```
    Calendar c = Calendar.getInstance();
    c.set(1900, 0, 1, 0, 0, 0);
    c.set(Calendar.MILLISECOND, 0);
    System.out.println(c.getTimeInMillis() / 1000);
    System.out.println(c.getTimeZone());
    DateTime dt = new DateTime(1900, 1, 1, 0, 0, 0);
    System.out.println(dt.getMillis() / 1000);
    System.out.println(dt.getChronology());
```

Output I get
```
-2209017600
sun.util.calendar.ZoneInfo[id="Asia/Shanghai",offset=28800000,dstSavings=0,useDaylight=false,transitions=19,lastRule=null]
-2209017952
ISOChronology[Asia/Shanghai]
```

**Comment by zjffdu** [comment]
Paste the stackoverflow link http://stackoverflow.com/questions/33996140/jodas-datetime-is-inconsistent-with-java-util-calendar/33996638?noredirect=1#comment55788673_33996638

**Comment by jodastephen** [comment]
Joda-Time uses the data from the IANA time-zone database without alteration. The JDK applies a cut-off for older dates. This means that for older dates, the two systems give different answers.
