### ISSUE TITLE
Cancun time zone is incorrect

### ISSUE THREAD

**Issue by master-elodin** [JodaOrg/joda-time#335]
America/Cancun time zone is incorrect in Joda Time 2.9.1. It should be -500 EST but is -600 CST. The time zone changed in February 2015. The release notes for 2.9.1 says"DateTimeZone data updated to version 2015g" but 2015g has the correct EST time zone.

http://www.joda.org/joda-time/timezones.html shows the incorrect CST time zone.

Doing this in Java also shows incorrect CST time zone:
DateTimeZone.forID("America/Cancun").getShortName(System.currentTimeMillis());

**Comment by jodastephen** [comment]
Given this code:

    DateTimeZone zone = DateTimeZone.forID("America/Cancun");
    System.out.println(DateTime.now(zone));
    System.out.println(zone.getShortName(System.currentTimeMillis()));

I get:

    2015-12-07T18:06:26.550-05:00
    CST

Thus, it is correctly choosing -05:00.

The "CST" is derived from data in the JDK, not from Joda-Time. Until the JDK is updated, that string will remain as "CST".
