### ISSUE TITLE
Release 2.9.1 is incomplete (no dist release)

### ISSUE THREAD

**Issue by martinm1000** [JodaOrg/joda-time#336]
Is that an error ?

**Comment by benkc** [comment]
Just came to report the same.

To get around this, I tried building 2.9.1 from sources, but got 74 errors relating to:

    error: package org.joda.convert does not exist

All of these have to do with two classes, FromString and ToString.  There *is* a package org.joda.time.convert, but it does not contain either of those two classes.

**Comment by martinm1000** [comment]
I'm too lazy to try to compile it ;-)

If this is automated and this doesn't compile... maybe its why that release only has source ?

**Comment by benkc** [comment]
Oh, could be!  Good insight. :)

**Comment by jodastephen** [comment]
Release updated with missing files.
