### ISSUE TITLE
LocalDate, timestamps and conversions

### ISSUE THREAD

**Issue by DanChaltiel** [JodaOrg/joda-time#338]
Hello the team !

I use conversion from and to long timestamps for storing dates in my database.
Hence, I have this issue :

```
LocalDate.now() //returns 2015-12-17, which is today
new LocalDate(LocalDate.now().toDate().getTime()); //returns 2015-12-16, which is yesterday
```

Can you reproduce this behavior ?
Is that a bug ?

At least this is very unexpected.
Conversions elsewhere in my application don't seem to go wrong though.

**Comment by jodastephen** [comment]
This can happen if the time-zone returned by `DateTimeZone.getDefault()` does not have the same rules as that returned by `TimeZone.getDefault()`.
