### ISSUE TITLE
Duration API doesn't have any helper methods for dealing with Weeks, Months, or Years

### ISSUE THREAD

**Issue by kluever** [JodaOrg/joda-time#341]
`Duration` has:
```
public long getStandardFoos() { ... }
public Foos toStandardFoos() { ... }
public static Duration standardFoos(long count) { ... }
```
...where `Foos` is `[Seconds, Minutes, Hours, Days]`

But it's missing the corresponding methods for `[Weeks, Months, Years]`. Is there a reason they aren't there?

**Comment by jodastephen** [comment]
Duration represents a number of seconds. There is no standard way to convert that to months or years as the length of a month varies.

**Comment by dlew** [comment]
Just out of curiosity - wouldn't there be a standard way to measure weeks? Or are there some situations where a standard week isn't 7 days?

**Comment by jodastephen** [comment]
A standard week would be 7 days, and the methods could be added. Its just that you have to draw a line somewhere when designing an API, and days is where it is drawn here.
