### ISSUE TITLE
Strange behavior with Week and Year

### ISSUE THREAD

**Issue by cteyton** [JodaOrg/joda-time#342]
Hi there, 

I encountered a strange scenario last Friday, January the 8th.
Here is my code : 

```java
//Last friday
DateTime dateFrom = new DateTime().withYear(2016).withDayOfMonth(8).withMonthOfYear(1);
//Get number of week and year
int prevWeek = dateFrom.getWeekOfWeekyear();
int prevYear = dateFrom.getYear();
//Values are prevWeek=1 and prevYear=2016 - 
new DateTime()
         .withYear(prevYear)
         .withWeekOfWeekyear(prevWeek);
//Nothing goes wrong

//Now i remove a week
dateFrom = dateFrom.minusWeeks(1).withMillisOfDay(1);
prevWeek = dateFrom.getWeekOfWeekyear();
prevYear = dateFrom.getYear();
//Values are prevWeek=53 and prevYear=2016 -
        new DateTime()
                .withYear(prevYear)
                .withWeekOfWeekyear(prevWeek);
//And here is the error !       
```

The error is :+1: 
```java
Exception in thread "main" org.joda.time.IllegalFieldValueException: Value 53 for weekOfWeekyear must be in the range [1,52]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:79)
	at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:496)
	at org.joda.time.DateTime.withWeekOfWeekyear(DateTime.java:1750)
        ...
```

Before getting an error, i remove one week to a date, and did not get an error here. So i assume that the date is correctly built. But then, when i create a new `DateTime` object with the previous values, now i get an error. 

Does it mean that the second `dateFrom` that results from the `minusWeek` operation is incorrect ? 

Sorry if this is not a bug and if i made a mistake.

Thanks.
Cédric

**Comment by alexandre3gomes** [comment]
When you create a new Date with prevYear and prevWeek, you are trying create a date on 53 week on 2016 year, but 2016 only have 52 weeks. in my opinion the error is on minusWeek operation, because if we subtract 1 of the first week of 2016, the correct result should be week 53 of 2015.

**Comment by alexandre3gomes** [comment]
I'm new here and wish contribute coding, I already cloned the repository, how can i assume this issue to try solve?

**Comment by jodastephen** [comment]
There looks to be no bug here. You should be using `getWeekyear()`, not `getYear()`, and `withWeekyear()` not `withYear()`. Read up about how ISO-8601 week-based years do not align with calendar years, and you should see how you went wrong.

**Comment by cteyton** [comment]
thanks for your answer, and sorry if this is not an issue.
