### ISSUE TITLE
Strange constructor behaviour for times right behind 1970

### ISSUE THREAD

**Issue by humfry** [JodaOrg/joda-time#348]
HI, I use the default timezone (MEZ +1[Berlin]) running on 64 bit Windows.
This code:

```java
   DateTime _dt1 = new DateTime(1970, 1 , 1, 0, 0, 0, 0 );
   System.out.println(_dt1.toString());

   DateTime _dt2 = new DateTime(1970, 1 , 1, 0, 20, 21, 0 );
   System.out.println(_dt2.toString());
```

produces this out put:
```
1970-01-01T00:00:00.000+01:00
292278994-08-17T07:12:55.807Z
```

Other values (near now( I didn't run a test through the centuries)) are working as expected.
What have I missed, or is it a bug or already an open issue?

**Comment by jodastephen** [comment]
Duplicate of #328 I think. Checkout v2.9.1

**Comment by humfry** [comment]
Ok. Duplicate.
Thanks
