### ISSUE TITLE
Add `isBeforeOrEqual` and `isEqualOrAfter` to `ReadableInstant`.

### ISSUE THREAD

**Issue by homeworkprod** [JodaOrg/joda-time#35]
The `ReadableInstant` interface only provides comparison methods representing the mathematical relations `<`, `=`, and `>`.

However, `<=` and `>=` are common as well, but they are not available as methods to compare instants with. This leads either to the creation of additional local utility methods (unfavorable), or to less readable, less expressive code like `!entity.getCreatedAt().isAfter(today)` (where the negation, `!`, is written far from the call to the method whose result value is to be negated, and thus too easily overlooked).

With the suggested methods, the above code be written more clearly as `entity.getCreatedAt().isBeforeOrEqual(today)`.

Please consider adding those methods. Dealing with date/time is already hard enough ;)

**Comment by bramdes** [comment]
tiny vote up. I could have used it. 
now doing ' !data1.isBefore(date2)'. instead of isEqualOrAfter
just bit less readable
