### ISSUE TITLE
LocalDate.toString() returns wrong date for dates on or after Feb 1 2016

### ISSUE THREAD

**Issue by sarismik** [JodaOrg/joda-time#352]
new LocalDate().toString("yyyy-MM-DD") returns "2016-02-32" when run today (Feb 1 2016), and unfortunately it doesn't get better for later dates - new LocalDate().plusDays(1).toString("yyyy-MM-DD") returns "2016-02-33" and new LocalDate().plusDays(100).toString("yyyy-MM-DD") returns "2016-05-132"!!!

I am using joda-time 2.9.2 and JDK/JRE 1.8.0_45.

**Comment by sarismik** [comment]
Sorry this may actually be a problem in the JDK! When I run the main class below (which has no dependency on joda-time), I also get the wrong date back - it prints 2016-02-32 - so it's likely you can close this issue and I'll take it up separately with Oracle :)

    public static void main(String[] args) {
        System.out.print(new SimpleDateFormat("yyyy-MM-DD").format(new Date()));
    }

**Comment by johnjaylward** [comment]
see if you can update to the latest JDK, mine is at 1.8.0_72 and I don't see a date issue

**Comment by johnjaylward** [comment]
wait, nevermind. I do see the same error with 1.8.0_72

**Comment by johnjaylward** [comment]
To be clear, I see it when outputting directly via the JDK. storing the dates into mysql appears to be working fine (which is what I checked first to ensure data integrity)

**Comment by jodastephen** [comment]
Upper case "D" means day-of-year, not day-of-month. Use lower case "d".

**Comment by johnjaylward** [comment]
ha, yes, I even checked the [API](http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html) and read it wrong there.
