### ISSUE TITLE
Cannot parse "1983-04-01": Illegal instant due to time zone offset transition (Asia/Novosibirsk)

### ISSUE THREAD

**Issue by golovishnikov** [JodaOrg/joda-time#356]
Some dates not parse for time zone Asia/Novosibirsk

Example:
```
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.format.DateTimeFormatter;
import org.joda.time.format.ISODateTimeFormat;

public void main(String[] args) throws Exception {
    DateTimeFormatter ISO_BASIC = ISODateTimeFormat.dateParser().withZone(DateTimeZone.forID("Asia/Novosibirsk"));
    DateTime dt = ISO_BASIC.parseDateTime("1983-04-01");
    DateTime ld = new DateTime(1983, 04, 01, 0, 0, 0, DateTimeZone.forID("Asia/Novosibirsk"));
}
```

Problems with 1982-04-01, 1983-04-01, 1984-04-01
But 1983-04-02 or 1983-03-01 is correct

**Comment by wokaokeji** [comment]
[http://joda-time.sourceforge.net/faq.html](url)

new LocalDate(date).toDateTimeAtStartOfDay()

**Comment by jodastephen** [comment]
Correct FAQ link - http://www.joda.org/joda-time/faq.html#illegalinstant

This [page](http://www.timeanddate.com/time/zone/russia/novosibirsk) shows when DST changes occur (select the 1980s from the drop down). Those dates had a DST change at midnight, thus 00:00 did not occur. I recommend using:

```
LocalDate./parse(str)toDateTimeAtStartOfDay()
```
