### ISSUE TITLE
DateTimeFormatter should be serializable.

### ISSUE THREAD

**Issue by adaviding** [JodaOrg/joda-time#358]
I am developing an Apache Spark application that requires the use of serializable lambda expressions.  For a lambda expression to be serializable at runtime, all of the variables that it captures must also be serializable.

In my application, I have an object that I want to be captured by the lambda expression, but I cannot make the object serializable because it contains lists of joda DateTimeFormatter objects, and these objects are not serializable.

My temporary workaround was to create a serializable config for my object, and pass the config into the lambda expression.  Unfortunately, the deserialization operation is expensive (the lambda expression is being evaluated repeatedly, and deserialization is being performed each time the lambda expression is evaluated).

The best workaround is to make the DateTimeFormatter implement java.io.Serializable.  This way, deserialization only happens once (when the lambda expression is deserialized).

This seems like an easy upgrade to joda.  It simply requires someone to mark a bunch of classes and interfaces as java.io.Serializable.  (The implementation is automatically handled by java.)

**Comment by nrinaudo** [comment]
Some of my users complain about the exact same problem with both Spark and Flink. Making DateTimeFormatter serialisable would be quite helpful and shouldn't break the API - but it might break binary compatibility?

**Comment by jodastephen** [comment]
Making formatter serializable is quite a big job as many inner classes are referenced. Each one would need to be considered to determine whether the serialised form is correct, and whether it deserialises correctly. In general, the advice is that serialization should not be undertaken lightly - it is an extension of your API.

In many cases, the textual formatter pattern can be retained and used for serialization instead.

**Comment by nrinaudo** [comment]
Well, that would be the ideal work around, yes, but my libraries expect instances of `DateTimeFormatter`, not `String` that are later converted to `DateTimeFormatter`. Unless `DateTimeFormatter` has some sort of `toPatternString` method that I shamefully failed to notice?

**Comment by jodastephen** [comment]
No there is no such method. Sorry I can't help make formatter serializable, as I said, it would be a mistake IMO.

**Comment by nrinaudo** [comment]
Understood. Thanks for answering so fast - even though I hoped for a different answer, having a definite _no_ is better than hoping for a _yes_ for months :)

**Comment by muralidcis** [comment]
@nrinaudo 
Iam sure you must be knowing but just consider regarding, the notes that says about joda time getting deprecated.
site:http://www.joda.org/joda-time/ 

 "Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project." 

Support: Note that Joda-Time is considered to be a largely “finished” project. No major enhancements are planned. If using Java SE 8, please migrate to java.time (JSR-310).
