### ISSUE TITLE
Feb 29 minus 3 days = Feb 25 --> correct ?

### ISSUE THREAD

**Issue by benoitbb** [JodaOrg/joda-time#363]
Can someone explain me why this assertion fail ?? (joda-time version 2.9.2)

        DateTimeZone zone = new DateTime(new Date()).getZone();

        // store in timestamp like this in database
        DateTime deadlineEndDt = new DateTime(1970, 1, 1, 22, 0, 0, 0, zone);

        DateTime deadlinePlusOffset = new DateTime(deadlineEndDt, zone)
                .withDayOfMonth(29)
                .withMonthOfYear(2)
                .withYear(2016)
                .minusDays(3);

        // failed -> return 25 instead of 26
        Assert.assertEquals(26, deadlinePlusOffset.get(DateTimeFieldType.dayOfMonth()));

#######################################
java.lang.AssertionError: 
Expected :26
Actual   :25

Thank you.

Regards,
Benoît

**Comment by broneill** [comment]
1970 wasn't a leap year. Each "with" method must return a valid DateTime object, and after setting the month to 2, the only valid date is 1970-02-28. Print the intermediate results and you'll see this.

**Comment by benoitbb** [comment]
Ok thank you for your answer.
I just have to do :

        DateTime deadlinePlusOffset = new DateTime(deadlineEndDt, zone)
                .withYear(2016)
                .withDayOfMonth(29)
                .withMonthOfYear(2)
                .minusDays(3);

Thank you.
