### ISSUE TITLE
DateTimeZone data should be updated to version 2016b

### ISSUE THREAD

**Issue by dbolshak** [JodaOrg/joda-time#365]
Dear Joda developers,

Could you please consider migrating to 2016b?

In release notes (http://www.joda.org/joda-time/upgradeto292.html) I've found
DateTimeZone data updated to version 2016a (version 2.9 had time-zone data 2015g)

But now version 2016b is available.

Best regards,
Denis

**Comment by larinam** [comment]
Hello, this is very important case for us, in Russia.

WBR,
Anton

**Comment by jodastephen** [comment]
Users of Joda-Time are expected to be able to update time-zone data themselves:
http://www.joda.org/joda-time/tz_update.html

When a new release occurs for other reasons, the time-zone data is updated.
