### ISSUE TITLE
class DateTimeConstants should use long type 

### ISSUE THREAD

**Issue by darknesstm** [JodaOrg/joda-time#369]
`DateTimeConstants.MILLIS_PER_DAY * 30` will be a negative number. `org.apache.commons.lang.time.DateUtils` do it right.

**Comment by jodastephen** [comment]
`DateTimeConstants.MILLIS_PER_DAY` fits into an `int`. That `DateTimeConstants.MILLIS_PER_DAY * 30` does not is the problem of the user writing that code. Joda-Time will not be making a backwards-incompatible change here.
