### ISSUE TITLE
The Class Seconds is working with Integer (should be Long)

### ISSUE THREAD

**Issue by gismoranas** [JodaOrg/joda-time#371]
### Key information

- version 2.9.3
- Result of `TimeZone.getDefault()`
Could not find class TimeZone
- Result of `DateTimeZone.getDefault()`
```
scala> org.joda.time.DateTimeZone.getDefault()
res84: org.joda.time.DateTimeZone = Europe/Berlin
```

### Problem description

Seconds should use long for internal calculations and as a result of getSeconds(), right? Even if there's another way to get the result using Intervals, it's not easy to predict when Seconds will work and when not. The same should apply to classes like Hours and Days much probably, just think what would happens if anybody were writing a science fiction game. Thanks! 

### Test case

```
scala> Seconds.secondsBetween(new DateTime(0), new DateTime(2100,1,1,0,0))
java.lang.ArithmeticException: Value cannot fit in an int: 4102441200
...
```

**Comment by jodastephen** [comment]
While I understand the overflow issue, this is a long-standing class. As such it cannot be changed without affecting backwards compatibility. Joda-Time is also replaced by `java.time` in Java SE 8, and as such, Joda-Time is no longer receiving enhancements.
