### ISSUE TITLE
 	java.lang.IllegalArgumentException: The datetime zone id 'asia/kolkata' is not recognised(Unable to convert Asia Timezone )

### ISSUE THREAD

**Issue by rishabhbsdei** [JodaOrg/joda-time#372]
We are unable to convert time from Asia time and it causes the below exception  	**java.lang.IllegalArgumentException: The datetime zone id 'asia/kolkata' is not recognised**

**Comment by jodastephen** [comment]
The ID is probably case sensitive - "Asia/Kolkata"
