### ISSUE TITLE
Day value of 31 not accepting and raising exception

### ISSUE THREAD

**Issue by sub-rat** [JodaOrg/joda-time#376]
While calculating the date range between two date points, I entered previous date and today date.

Today being 31st May 2016, the library crashes giving the following exception. 

> 05-31 19:50:39.462 28036-28036/com.* E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                        org.joda.time.IllegalFieldValueException: Value 31 for dayOfMonth must be in the range [1,30]
>                                                                            at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:252)
>                                                                            at org.joda.time.chrono.BasicChronology.getDateMidnightMillis(BasicChronology.java:632)
>                                                                            at org.joda.time.chrono.BasicChronology.getDateTimeMillis0(BasicChronology.java:186)
>                                                                            at org.joda.time.chrono.BasicChronology.getDateTimeMillis(BasicChronology.java:160)
>                                                                            at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:120)
>                                                                            at org.joda.time.LocalDate.<init>(LocalDate.java:457)
>                                                                            at org.joda.time.LocalDate.<init>(LocalDate.java:436)

**Comment by utibeng** [comment]
@sub-rat I've been unable to reproduce the error for the month of May. It only occurs when I choose a 30 day month like April. Can you paste the code line that's giving the error?

**Comment by jodastephen** [comment]
Without a test case this issue will be closed.

**Comment by janbolat** [comment]
@jodastephen My app crashes due to the same problem:
![image](https://user-images.githubusercontent.com/6511056/69301870-d7bb3800-0c41-11ea-932e-ed073679df8c.png)

**Comment by jodastephen** [comment]
Without an [sscce test case](http://sscce.org/) I can't do anything. In all probability you are trying to set day 31 of a 30 day month, whichJoda-Time understandably rejects.

**Comment by janbolat** [comment]
Ok, I understand. Anyway the number of days in a month is calculated with
joda. Then it doesn't return the correct number
