### ISSUE TITLE
Conversion from TimeZone to DateTimeZone fails in Arabic locale

### ISSUE THREAD

**Issue by dalewking** [JodaOrg/joda-time#381]
### Key information
- Joda-Time version: 2.8.2
### Problem description

Our code has some verification code to verify that time conversions work correctly. We are getting crashes in the field apparently when the user's phone is set to Arabic language.

The test case is simply:

```
TimeZone timeZone = TimeZone.getTimeZone("GMT-0800");
DateTimeZone dateTimeZone = DateTimeZone.forTimeZone(timeZone);
```

This crashes with:

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid format: "-٠٨:٠٠" is malformed at "٠٨:٠٠"
       at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
       at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
       at org.joda.time.DateTimeZone.parseOffset(DateTimeZone.java:612)
       at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:365)
```

"٠٨:٠٠" is 08:00 in Arabic. Apparently TimeZone internally stores the 0800 using the Arabic numerals, which you fail to parse.

**Comment by jodastephen** [comment]
I have tried using each locale in Java 8 and not been able to reproduce the problem:

    for (Locale loc : Locale.getAvailableLocales()) {
        Locale.setDefault(loc);
        TimeZone timeZone = TimeZone.getTimeZone("GMT-0800");
        DateTimeZone dateTimeZone = DateTimeZone.forTimeZone(timeZone);
        System.out.println(dateTimeZone);
    }

Without further information, this issue will be closed.

**Comment by dalewking** [comment]
Note we found the problem on Android, if that matters. I haven't actually tried to recreate it, but we have crash reports for it.

**Comment by dalewking** [comment]
OK, I created an Android project that demonstrates the problem if you run it on an Android Lollipop device or emulator and set the language to Arabic.

See https://gitlab.com/dalewking/JodaTest

**Comment by dalewking** [comment]
Any progress on this? We are working on releasing Arabic support and this is a problem.

**Comment by jodastephen** [comment]
I tried the android project but struggled. I hope the change made fixes the problem.

**Comment by dalewking** [comment]
To follow up, yes it did fix the problem.
