### ISSUE TITLE
DateTimeFormatter.parseDateTime() accepts illegal date string

### ISSUE THREAD

**Issue by adriangay** [JodaOrg/joda-time#384]
- Joda-Time version: joda-time-2.8.2.jar

### Problem description
 
JUnit test below is self-explanatory. Result of tests is:

```
TimeZone.getDefault(): sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
DateTimeZone.getDefault(): Europe/London

java.lang.AssertionError: Invalid date string 'Sun Jul 04 2016' did not cause IllegalArgumentException; actual parseDateTime() conversion was: Sun Jul 10 2016
`
```
		try {
			System.out.println("TimeZone.getDefault(): " + TimeZone.getDefault());
			System.out.println("DateTimeZone.getDefault(): " + DateTimeZone.getDefault());
			String pattern = "EEE MMM dd yyyy";
			String invalidDateString = "Sun Jul 04 2016";
			//	4th July 2016 was a Monday! 
			DateTime x = DateTimeFormat.forPattern(pattern).parseDateTime(invalidDateString);
			Fail.fail("Invalid date string '" + invalidDateString + "' did not cause IllegalArgumentException; actual parseDateTime() conversion was: " + DateTimeFormat.forPattern(pattern).print(x));
		}
		catch (Exception e) {
			assertTrue("Unexpected Exception: ", e instanceof IllegalArgumentException);
		}

```

**Comment by jodastephen** [comment]
Joda-Time has always leniently accepts invalid input such as this. This behaviour will not be changed at this point. JSR-310 by contrast, throws an exception, or allows users to choose which fields to ignore when resolving.

**Comment by adriangay** [comment]
ok, thanks for answering :)
