### ISSUE TITLE
Translation of Tuesday in Finnish is wrong

### ISSUE THREAD

**Issue by frmz** [JodaOrg/joda-time#389]
Translation of Tuesday in Finnish when using "EEEE" in formatter seems to be wrong, it prints out "Tiistaina" instead it should print "Tiistai". Tiistaina means "on tuesday".

To reproduce:

        Locale locale = new Locale("fi","fi");
        MutableDateTime start = new MutableDateTime();
        start.setDayOfWeek(DateTimeConstants.TUESDAY);
        start.dayOfWeek().getAsText(locale)

**Comment by gauravsak** [comment]
Verified with [Google Translate](https://www.google.com/#q=tiistaina+translation) as well.

**Comment by jodastephen** [comment]
Joda-Time gets this data from the JDK. If the JDK data is wrong, there is nothing we can do.

**Comment by gauravsak** [comment]
@jodastephen Should this issue be closed then?

**Comment by frmz** [comment]
This might be a JDK issue in the user env then, closing
