### ISSUE TITLE
Printing the date "1753-01-01 00:00:00.123" gets printed incorrectly when the input timestamp is passed and printed using the DateTimeFormatter

### ISSUE THREAD

**Issue by srikanthvedanthi** [JodaOrg/joda-time#395]
### Key information

- Joda-Time version : 2.9.4

- Result of `TimeZone.getDefault()`
 sun.util.calendar.ZoneInfo[id="Asia/Calcutta",offset=19800000,dstSavings=0,useDaylight=false,transitions=6,lastRule=null]

- Result of `DateTimeZone.getDefault()`
Asia/Kolkata

### Problem description

Printing the date "1753-01-01 00:00:00.123" gets printed incorrectly when the input timestamp is passed and printed using the DateTimeFormatter

Sample code:
public static void main( String[] args ) {
        Timestamp ts = Timestamp.valueOf( "1753-01-01 00:00:00.123" );
        System.out.println(ts);
        String sts = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss.SSS").print( ts.getTime() );
        System.out.println(sts);
    }

Output:
1753-01-01 00:00:00.123
1753-01-01 00:23:28.123

### Test case

Instant: 1753-01-01 00:00:00.123 or something similar

Formatter:
DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss.SSS")

API: print(java.sqlTimestamp)

**Comment by jodastephen** [comment]
Old timestamps differ between the JDK and Joda-Time. The JDK uses a fixed offset prior to 1900, whereas Joda-Time uses the full historical data from the time-zone database, including LMT (local mean time).

See also #80
