### ISSUE TITLE
Joda-time relies on deafult locale

### ISSUE THREAD

**Issue by kal0ian** [JodaOrg/joda-time#397]
In ZoneInfoCompiler class at line 210 is not used proper toLower()/toUpper(). The issue is that if the server relies on the default locale and if the process was started with some non English compatible locale such as Turkish, toUpper/Lower will yield an incorrect result. For instance "URI".toLowerCase() will result in "urı" instead of "uri". The same applies to toUpperCase -> "uri".toUpperCase() will become "URİ" and checks like "string.toUpperCase().equals(someConstant)" will fail.

VERSION OF Joda-time is 2.7

**Comment by jodastephen** [comment]
Fixed thanks
