### ISSUE TITLE
Prevent formatting of periods that is not conform to the ISO8601 standard

### ISSUE THREAD

**Issue by tokou** [JodaOrg/joda-time#400]
### Key information

- Joda-Time version
v2.9.4

- Result of `TimeZone.getDefault()`
`libcore.util.ZoneInfo[id="America/New_York",mRawOffset=-18000000,mEarliestRawOffset=-18000000,mUseDst=true,mDstSavings=3600000,transitions=235] `

- Result of `DateTimeZone.getDefault()`
`America/New_York`

### Problem description

Formatting of ISO8601 periods does not conform to ISO8601 standard.

According to the ISO8601 standard, a period can be formatted with **only one of the two following** formats :

- P[n]Y[n]M[n]DT[n]H[n]M[n]S
- P[n]W

> Durations are represented by the format P[n]Y[n]M[n]DT[n]H[n]M[n]S or P[n]W
[Source](https://en.wikipedia.org/wiki/ISO_8601#Durations)

Hence, the format P[n]Y[n]M[n]W[n]DT[n]H[n]M[n]S is not a valid period format according to ISO8601 (weeks cannot be mixed with any other date or time designator)

The library should check for fields in the Period class and prevent formatting them if they have both a week field and one of the other date or hour fields.

### Test case

See [this test file](https://github.com/JodaOrg/joda-time/blob/master/src/test/java/org/joda/time/format/TestISOPeriodFormat.java#L101)

**Comment by jodastephen** [comment]
Users can use `PeriodType` to create instances of `Period` with or without weeks. The formatter simply outputs a representation of the `Period` object it is given in an IDO-8601-like style. There is no suitable change to make here.
