### ISSUE TITLE
AbstractDuration isEqual/isLongerThan/isShorterThan documentation

### ISSUE THREAD

**Issue by monarchdodra** [JodaOrg/joda-time#401]
### Key information
- Joda-Time version 2.2 / HEAD

### Test case
Duration myDuration = Duration.standardDays(1)
if (myDuration.isGreaterThan(Duration.standardDays(1))) {...}

### Problem description
The description for all three of "isEqual/isLongerThan/isShorterThan" reads:
"Returns: true if this duration is equal to than the duration passed in"

This is neither correct English, nor does it correctly describe isLongerThan and isShorterThan. These should read (respectively):
"Returns: true if this duration is equal to the duration passed in"
"Returns: true if this duration is strictly greater than the duration passed in"
"Returns: true if this duration is strictly shorter than the duration passed in"

While this might seem obvious, My test case was writing:
if (myDuration.isGreaterThan(Duration.standardDays(1))) {...}

In which case, I was not quite sure if the comparison was strict (>) or with equal (>=). The provided documentation was not clear enough for me to figure out the provided behavior, and I had to look at the code to know. So having the word "strictly" in there too would be important.

**Comment by monarchdodra** [comment]
Edit: I'm seeing this was partially fixed in 2014 (https://github.com/JodaOrg/joda-time/commit/99b73f9e56b251f853b2c5a6c89d9b27241c7797 but no mention of "strict").

I was looking at the sourceforge documentation:
https://github.com/JodaOrg/joda-time/commit/99b73f9e56b251f853b2c5a6c89d9b27241c7797

Which seems to have not been updated since 2.2?

**Comment by jodastephen** [comment]
Thanks. The code left sourceforge a long time ago. Not sure I have the rights to update it now.
