### ISSUE TITLE
need to update to latest timezone data (2016h) to pick up Turkey DST rule change

### ISSUE THREAD

**Issue by rahulpratapm** [JodaOrg/joda-time#403]
### Key information
- Joda-Time version
  2.9.4
- Result of `TimeZone.getDefault()`
  sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]
- Result of `DateTimeZone.getDefault()`
  UTC
### Problem description

Latest version of Joda-Time does not include 2016g timezone data. Specifically, it doesn't reflect Turkey's decision to permanently remain on UTC+3 (See http://www.oracle.com/technetwork/java/javase/tzdata-versions-138805.html: Turkey switched from EET/EEST (+02/+03) to permanent +03, effective 2016-09-07.)
### Test case

Scala code below:

```
import org.joda.time._

val turkeyTz = DateTimeZone.forID("Europe/Istanbul")

val now = new DateTime(turkeyTz)
val offsetNow = turkeyTz.getOffset(now) / 1000 / 60

val later = new DateTime(2016, 10, 30, 5, 0, turkeyTz)
val offsetLater = turkeyTz.getOffset(later) / 1000 / 60
```

Current output:

```
turkeyTz: org.joda.time.DateTimeZone = Europe/Istanbul
now: org.joda.time.DateTime = 2016-10-27T19:57:06.583+03:00
offsetNow: Int = 180
later: org.joda.time.DateTime = 2016-10-30T05:00:00.000+02:00
offsetLater: Int = 120
```

Expected output is that `offsetLater` is also `180`

**Comment by jodastephen** [comment]
Joda-Time users are expected to be able to follow [these instructions](http://www.joda.org/joda-time/tz_update.html) to keep the time-zone data up to date. A new release will occur at some point, but I never make commitments as to when.

**Comment by rahulpratapm** [comment]
Thanks, Stephen. We did that at our end. We just added the issue to hopefully expedite the process of getting this into a standard release.

**Comment by jodastephen** [comment]
Updated to 2016i

**Comment by weaselmetal** [comment]
for those looking for the version that addresses this, it's version 2.9.5.
http://www.joda.org/joda-time/upgradeto295.html

> DateTimeZone data updated to version 2016i

**Comment by perry83** [comment]
Your documentation (https://www.joda.org/joda-time/timezones.html) still says that there is:
+02:00 | Europe/Istanbul | Asia/Istanbul, Turkey
