### ISSUE TITLE
Duration.getStandard* methods have wrong JavaDoc comments

### ISSUE THREAD

**Issue by mghoffmann** [JodaOrg/joda-time#405]
### Problem description
This isn't a run-time problem, so I didn't include any code results. The Duration class has the following methods:
```
getStandardDays
getStandardHours
getStandardMinutes
getStandardSeconds
```
In the JavaDoc comments, each of them has the following line:
```
* @return the length of the duration in standard seconds
```
This comment is only true for the `getStandardSeconds` method. The others should say that they return the length of the durations in their respective units, i.e.
```
* @return the length of the duration in standard hours
```
for the getStandardHours method.

**Comment by jodastephen** [comment]
Fixed by #388
