### ISSUE TITLE
Value set with MutableDateTime.hourOfDay().set() is cleared in corresponding DateTime

### ISSUE THREAD

**Issue by mhdirkse** [JodaOrg/joda-time#407]
Dear madam / sir,

I think MutableDateTime has a problem with the hour of the day. I tried the following code:

    MutableDateTime mref = new MutableDateTime();
    mref.setYear(2016);
    mref.setMonthOfYear(12);
    mref.setDayOfMonth(13);
    mref.hourOfDay().set(4);
    mref.setMinuteOfDay(15);
    mref.setSecondOfMinute(49);
    mref.setMillisOfSecond(345);
    mref.setZone(DateTimeZone.forID("CET"));
    reference = mref.toDateTime();
    System.out.println(String.format("Year, month and day: %d-%d-%d",
        reference.getYear(), reference.getMonthOfYear(), reference.getDayOfMonth()));
    System.out.println(String.format("Hour, minute, second and millis: %d:%d:%d.%d",
        reference.getHourOfDay(), reference.getMinuteOfHour(), reference.getSecondOfMinute(),
        reference.getMillisOfSecond()));

It produces:

Year, month and day: 2016-12-13
Hour, minute, second and millis: 0:15:49.345

The last line is wrong: I would expect 4:15:49.345. I see also 0 for the hours when I use
    mref.hourOfDay().set(3);

With kind regards,

Martijn Dirkse

**Comment by mhdirkse** [comment]
I forgot to tell that I am working with Java 7.

**Comment by jodastephen** [comment]
You are using `setMinuteOfDay` when you should be using `setMinuteOfHour`. Setting the minute-of-day wipes out the previously set hour-of-day.

**Comment by mhdirkse** [comment]
Thank you for answering to my issue. I understand your point and thank you for your time.
