### ISSUE TITLE
Problem with Buckminster install (maven)

### ISSUE THREAD

**Issue by SangreNegra** [JodaOrg/joda-time#408]
Hello Stephen,

my problem might not be actually a bug in joda time, rather a maven central repository issue specific to the latest joda time release. And this happens only with joda time.

When installing joda time with Buckminster in Eclipse from a materialize file I get the following errors while eclipse tries to download joda time:

Connection to http://central.maven.org/maven2/joda-time/joda-time/maven-metadata.xml failed on Invalid last modified value. Retry attempt 1 started
Connection to http://central.maven.org/maven2/joda-time/joda-time/maven-metadata.xml failed on Invalid last modified value. Retry attempt 2 started
Connection to http://central.maven.org/maven2/joda-time/joda-time/maven-metadata.xml failed on Invalid last modified value. Retry attempt 3 started
ERROR   [0049] : No suitable provider for component joda-time:osgi.bundle was found in resourceMap file:/home/jgubo/dev/java/idempiere/org.adempiere.sdk-feature/adempiere.rmap
  ERROR   [0049] : No suitable provider for component joda-time:osgi.bundle was found in searchPath bundles.maven
    ERROR   [0049] : Rejecting provider maven2(${url.maven2}/maven2[http://central.maven.org/maven2]): No component match was found
      ERROR   Could not connect to http://central.maven.org/maven2/joda-time/joda-time/maven-metadata.xml
Attempt to use an unresolved node. Request is joda-time:osgi.bundle

You help is greatly appreciated! Thanks and merry xmas :100: 

Regards Johannes

**Comment by hieplq** [comment]
@SangreNegra, work-around solution here https://idempiere.atlassian.net/browse/IDEMPIERE-3277

**Comment by jodastephen** [comment]
https://issues.sonatype.org/browse/OSSRH-27347

**Comment by SangreNegra** [comment]
Thank you Stephen for filing a bug report.


2017-01-03 13:34 GMT+01:00 Stephen Colebourne <notifications@github.com>:
