### ISSUE TITLE
DateTimePrinterInternalPrinter appends the text twice if appending to a StringBuffer or Writer

### ISSUE THREAD

**Issue by trejkaz** [JodaOrg/joda-time#409]
### Key information

- Joda-Time version - I'm using 2.9.7, but you can see the problem by reading the current master as well.
- Time zone not important

### Problem description

`DateTimePrinterInternalPrinter#printTo` is implemented as follows:

        public void printTo(Appendable appendable, ReadablePartial partial, Locale locale) throws IOException {
            if (appendable instanceof StringBuffer) {
                StringBuffer buf = (StringBuffer) appendable;
                underlying.printTo(buf, partial, locale);
            }
            if (appendable instanceof Writer) {
                Writer out = (Writer) appendable;
                underlying.printTo(out, partial, locale);
            }
            StringBuffer buf = new StringBuffer(estimatePrintedLength());
            underlying.printTo(buf, partial, locale);
            appendable.append(buf);
        }

The other override has the same problem.

Since neither if-block returns after appending, if you do pass in something which is a StringBuffer or a Writer, you end up with the text coming out twice in the resulting formatted date.

### Test case

    @Test
    public void testCustomDateTimePrinter() {
        DateTimePrinter printer = new DateTimeFormatterBuilder()
                .append(new CustomDateTimePrinter())
                .appendLiteral(' ')
                .appendYear(4, 8)
                .toPrinter();

        StringBuffer buffer = new StringBuffer();
        DateTimeZone zone = DateTimeZone.UTC;
        Chronology chronology = ISOChronology.getInstance(zone);
        long instant = new DateTime(2017, 1, 1, 0, 0, 0, chronology).getMillis();
        printer.printTo(buffer, instant, chronology, 0, zone, Locale.ROOT);

        assertThat(buffer.toString(), is(equalTo("Hi 2017")));
    }

    private static class CustomDateTimePrinter implements DateTimePrinter {
        @Override
        public int estimatePrintedLength() {
            return 2;
        }

        @Override
        public void printTo(StringBuffer buf, long instant, Chronology chrono, int displayOffset, DateTimeZone displayZone, Locale locale) {
            buf.append("Hi");
        }

        @Override
        public void printTo(Writer out, long instant, Chronology chrono, int displayOffset, DateTimeZone displayZone, Locale locale) throws IOException {
            out.write("Hi");
        }

        @Override
        public void printTo(StringBuffer buf, ReadablePartial partial, Locale locale) {
            buf.append("Hi");
        }

        @Override
        public void printTo(Writer out, ReadablePartial partial, Locale locale) throws IOException {
            out.write("hi");
        }
    }

### Result

    java.lang.AssertionError: 
    Expected: is "Hi 2017"
         but: was "HiHi 2017"

### Workaround

Not entirely sure. I'd say pass in another kind of Appendable (like StringBuilder), but it looks like the external API just doesn't let me pass in any kind. :(

**Comment by jodastephen** [comment]
Fixed, thanks
