### ISSUE TITLE
Problem getting specific date from last year (2016)

### ISSUE THREAD

**Issue by MatejScolopax** [JodaOrg/joda-time#410]
### Key information

- Joda-Time version : joda-time-2.9.7
- Result of `TimeZone.getDefault()` :sun.util.calendar.ZoneInfo[id="Europe/Prague",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=141,lastRule=java.util.SimpleTimeZone[id=Europe/Prague,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
- Result of `DateTimeZone.getDefault()` :Europe/Prague

### Problem description

Getting specific date for year 2016 using methods withYear, withWeekOfWeekyear and withDayOfWeek results with date for year 2015

### Test case
`public class Main {

	public static void main(String[] args) {

		int weekNumber = 21;
		DateTime dtNow = new DateTime();
		DateTime dt0 = new DateTime().withYear(2014).withWeekOfWeekyear(weekNumber).withDayOfWeek(DateTimeConstants.MONDAY);
		DateTime dt1 = new DateTime().withYear(2015).withWeekOfWeekyear(weekNumber).withDayOfWeek(DateTimeConstants.MONDAY);
		DateTime dt2 = new DateTime().withYear(2016).withWeekOfWeekyear(weekNumber).withDayOfWeek(DateTimeConstants.MONDAY);
		DateTime dt3 = new DateTime().withYear(2017).withWeekOfWeekyear(weekNumber).withDayOfWeek(DateTimeConstants.MONDAY);
		DateTime dt4 = new DateTime().withYear(2018).withWeekOfWeekyear(weekNumber).withDayOfWeek(DateTimeConstants.MONDAY);
		
		SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy", Locale.ENGLISH);
		System.out.println("dtNow (2017) : " + sdf.format(dtNow.toDate()));
		System.out.println("dt0   (2014) : " + sdf.format(dt0.toDate()));
		System.out.println("dt1   (2015) : " + sdf.format(dt1.toDate()));
		System.out.println("dt2   (2016) : " + sdf.format(dt2.toDate()) + " expected: 23.05.2016" );
		System.out.println("dt3   (2017) : " + sdf.format(dt3.toDate()));
		System.out.println("dt4   (2018) : " + sdf.format(dt4.toDate()));
		
	}
}`
### Result

dtNow (2017) : 03.01.2017
dt0   (2014) : 19.05.2014
dt1   (2015) : 18.05.2015
**dt2   (2016) : 18.05.2015 expected: 23.05.2016**
dt3   (2017) : 22.05.2017
dt4   (2018) : 21.05.2018

**Comment by MenoData** [comment]
This is very similar to this [SO-post](http://stackoverflow.com/questions/41429998/jodatime-will-always-change-to-2015-if-withyear-set-to-2016). Not a bug.
