### ISSUE TITLE
"YYYMM.ww" formatter returns wrong DateTime for "201701.05"

### ISSUE THREAD

**Issue by metacret** [JodaOrg/joda-time#411]
DateTimeFormat.forPatterns("YYYYMM.ww").parseDateTime("201701.05") returns "1454313600000", which is 2016-02-01.

**Comment by MenoData** [comment]
You have to use x instead of Y (Joda-Time uses a different pattern syntax, see [javadoc](http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html)).

**Comment by metacret** [comment]
@MenoData thank you so much!
