### ISSUE TITLE
patch to make joda-time 2.0 unit tests pass on Java 8

### ISSUE THREAD

**Issue by billsmith** [JodaOrg/joda-time#413]
I found a Java 8 incompatibility in joda-time 2.0 while switching a large number of projects to the Java 8 runtime.  Rather than upgrade to a new joda-time, I patched joda-time 2.0.  (We'll deal with switching to Java 8's java.time package later.)

Our patched version is at https://github.com/indeedeng/joda-time.

**Comment by jodastephen** [comment]
Joda-Time has not used source forge for many years. Please try the latest version from GitHub or Maven Central.

**Comment by billsmith** [comment]
Thank you Stephen.  I am aware of newer versions of joda-time as well as the java.time package in Java 8.    The specific bug I encountered was fixed in joda-time 2.8.1.  I was not in a position to upgrade my large code base to a newer joda-time version, so I patched  the version we already had.  I offered my patch back to the community just in case someone else was in a similar predicament.

**Comment by jodastephen** [comment]
Ok, great thanks
