### ISSUE TITLE
AbstractDateTime#getMillisOfDay returns incorrect value on DST days

### ISSUE THREAD

**Issue by Singleton06** [JodaOrg/joda-time#415]
### Key information
- Joda-Time version: 2.9.2
- Result of `TimeZone.getDefault()`
> sun.util.calendar.ZoneInfo[id="America/Chicago",offset=-21600000,dstSavings=3600000,useDaylight=true,transitions=235,lastRule=java.util.SimpleTimeZone[id=America/Chicago,offset=-21600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]]

- Result of `DateTimeZone.getDefault()`
America/Chicago

### Problem description
When getting the milliseconds of the day, it appears that it does not correctly account for the milliseconds of the day when that day is a DST transition date.

There is a chance that I am misunderstanding the intended purpose of the org.joda.time.base.AbstractDateTime#getMillisOfDay() method.  My expectation is that the getMillisOfDay would essentially create an interval between the current value within the DateTime and a DateTime that represents the beginning of DateTime that the method is invoked on (in the same time zone, etc), then a duration is calculated between the two.  The follow test case shows that this is not the actual behavior. 

### Test case
```java
        DateTime dstDate = new DateTime(2017, 3, 12, 6, 0);
        DateTime nonDSTDate = new DateTime(2017, 3, 11, 6, 0);
        System.out.println(dstDate); // 2017-03-12T06:00:00.000-05:00
        System.out.println(nonDSTDate); // 2017-03-11T06:00:00.000-06:00
        
        System.out.println(dstDate.getMillisOfDay()); // 21600000
        System.out.println(nonDSTDate.getMillisOfDay()); // 21600000
        
        DateTime dstDateStartOfDay = new DateTime(2017, 3, 12, 0, 0);
        DateTime nonDSTDateStartOfDay = new DateTime(2017, 3, 11, 0, 0);
        System.out.println(new Interval(dstDateStartOfDay, dstDate).toDurationMillis()); // 18000000
        System.out.println(new Interval(nonDSTDateStartOfDay, nonDSTDate).toDurationMillis()); // 21600000
```

I have inlined comments that show the output, but here is the full output as well:
```plaintext
2017-03-12T06:00:00.000-05:00
2017-03-11T06:00:00.000-06:00
21600000
21600000
18000000
21600000
```

The expected output would be that the print out of the dstDate's millis of day would have a different value than the non-dst-date's millis of the day.

**Comment by jodastephen** [comment]
Joda-Time is correct. The `millisOfDay` field is a breakdown of the `LocalTime`, not a count of milliseconds since midnight. (Note that midnight does not necessarily exist as a DST change may make midnight disappear). I've added some extra documentation.
