### ISSUE TITLE
DateTIme construct return current time when parameter is null

### ISSUE THREAD

**Issue by linbeisaii** [JodaOrg/joda-time#417]
Joda-Time version 2.9.3 

### Problem description
DateTime constructor 
public DateTime(Object instant) {
        super(instant, (Chronology) null);
}

 when the instant is not null, this return value is correct. 
 but when the instant is null, return value is current time that I think is a bug

### Test case
        Date date = DateTime.parse("2017-01-01").toDate();
        System.out.println(date); // Sun Jan 01 00:00:00 CST 2017

        date = null;
        System.out.println(new DateTime(date)); //2017-03-06T22:43:56.089+08:00

**Comment by jodastephen** [comment]
In Joda-Time, null is the same as the current instant.
