### ISSUE TITLE
DateTimeFormatterBuilder bugged when using DateTimeFormatter with Locale

### ISSUE THREAD

**Issue by dannyyw** [JodaOrg/joda-time#431]
### Key information
- 2.9.9 (also tested in multiple previous versions and same problem)

### Problem description
It seems that using the DateTimeFormatterBuilder will ignore the Locale of any formatter/parser set into it.

### Test case

String testDate = "Juli";
DateTimeFormatter f = DateTimeFormat.forPattern("MMMM").withLocale(Locale.GERMAN);
DateTime date = f.parseDateTime(testDate);
//This case is parsed correctly with the assigned Locale
System.out.println(date);

DateTimeFormatter formatter = new DateTimeFormatterBuilder().append( f ).toFormatter();
DateTime date1 = formatter.parseDateTime( testDate );
//This case gives an error.. why?
System.out.println(date1);

The reason I want to use the DateTimeFormatterBuilder is because I want to assign multiple parsers to check and avoid trying one by one and catching errors. For example code:
DateTimeParser[] parsers = { 
DateTimeFormat.forPattern( "MMMM" ).withLocale(Locale.GERMAN).getParser()  };
DateTimeFormatter formatter = new DateTimeFormatterBuilder().append( null, parsers ).toFormatter();

Edit:
In fact seems to happen that any alteration to the DateTimeFormat before the getParser() is ignored.
For example:
//1) this case works fine and the resulting date will have set year 2017
DateTimeFormatter f = DateTimeFormat.forPattern("dd.MM").withDefaultYear(2017);

//2) this case will ignore the year and leave it as 2000
DateTimeParser[] parsers = { 
DateTimeFormat.forPattern( "dd.MM" ).withDefaultYear(Year.now().getValue()).getParser()	
};
DateTimeFormatter formatter = new DateTimeFormatterBuilder().append( null, parsers ).toFormatter();

**Comment by jodastephen** [comment]
The Javadoc of the `append(DateTimeFormatter)` method says

    Note however that any formatter specific information, such as the locale,
    time-zone, chronology, offset parsing or pivot/default year, will not be
    extracted by this method

There is a similar comment on other methods like `append(DateTimeParser)`.

As such, the code is behaving as intended, if not as you desire.
