### ISSUE TITLE
PersianChronology 

### ISSUE THREAD

**Issue by mjal146** [JodaOrg/joda-time#435]
Do you intend to add and support the Persian calendar?

**Comment by jodastephen** [comment]
For anyone reaching this via Google, I have no plans to add the Persian calendar.

**Comment by sindoc** [comment]
Looks like something @zubinkavarana could help with, starting with a pull request?
http://zubinkavarana.github.io/joda-time/
https://github.com/zubinkavarana/joda-time/

He seems to already have forked Joda Time to add the Persian chronology.

**Comment by zubinkavarana** [comment]
I can only advise in general terms at this time - 

1. Use the formula specified at [Borkowski paper](http://www.astro.uni.torun.pl/~kb/Papers/EMP/PersianC-EMP.htm)
2. Write your own chronology and deploy it separately in another library jar alongside the main joda one. You can use the repo above to see how it was done
3. Make sure all the tests pass 

Best wishes

**Comment by mohamadian** [comment]
You can use this library:
   https://github.com/mohamadian/PersianJodaTime

it is based on JodaTime and zubinkavarana/JodaTime.

**Comment by mjal146** [comment]
thanks a lot

 

    On Sunday, October 29, 2017, 7:05:46 PM GMT+3:30, Mahdi Mohamadian <notifications@github.com> wrote:  
 
 
You can use this library:
https://github.com/mohamadian/PersianJodaTime

it is based on JodaTime and zubinkavarana/JodaTime.
