### ISSUE TITLE
MinusMonth issue when result is in the end of February

### ISSUE THREAD

**Issue by Dionsaurus** [JodaOrg/joda-time#441]
Hi Team,

I'd like to reporting an issue about minusMonths method. I found this when I investigated some unit tests that were failing on certain day of our automated build process.

So I write this unit test for simplicity:

    private static final String YYYY_MM_DD = "yyyy-MM-dd";
    
    @Test
    public void test_minus_months() {
 	   DateTime strangeCase1 = DateTime.parse("2015-03-30", DateTimeFormat.forPattern(YYYY_MM_DD));
 	   DateTime strangeCase2 = DateTime.parse("2015-03-29", DateTimeFormat.forPattern(YYYY_MM_DD));
 	   DateTime strangeCase3 = DateTime.parse("2015-03-28", DateTimeFormat.forPattern(YYYY_MM_DD));
 	   DateTime oldTime = DateTime.parse("2015-02-28", DateTimeFormat.forPattern(YYYY_MM_DD));
 	   assertEquals(oldTime, strangeCase1.minusMonths(1));
 	   assertEquals(oldTime, strangeCase2.minusMonths(1));
 	   assertEquals(oldTime, strangeCase3.minusMonths(1));
    }

And this test run successfully, which I believe it shouldn't. Three different days, when one month subtracted from them using minusMonth, resulting in the same day. 

I'm using version 2.9 and when I changed to 2.9.9, this issue still exists.

**Comment by jodastephen** [comment]
Not sure what else you'd expect. There is no such date as the 30th February.
