### ISSUE TITLE
Days.daysBetween returns unexpected value when you compare two dates where it was applied minusDays(1) to one of them

### ISSUE THREAD

**Issue by jtymoschuk** [JodaOrg/joda-time#442]
### Key information

- Joda-Time version: **2.9.9**
- Result of `TimeZone.getDefault()`: **Europe/Berlin**
- Result of `DateTimeZone.getDefault()`: **Europe/Berlin**

### Case
Given this construction **Days.daysBetween(DateTime.now(),  DateTime.now().minusDays(1)).getValue()** I would expect to receive 1 as a result, but it returns 0

**Comment by jodastephen** [comment]
You call `DateTime.now()` twice. Between the two calls, time moves forward. Thus you end up calculating the days between `2017-09-15T11:29:12.860+02:00` and `2017-09-14T11:29:12.879+02:00` (for example). As can be seen, this is 19 milliseconds less than one day.

The correct code is to call `now()` once:

    DateTime now = DateTime.now();
    int days = Days.daysBetween(now, now.minusDays(1)).getDays();

Note that this is a general rule for all date-time code - call `now()` once when you need consistency.
