### ISSUE TITLE
FR: Instant static factory methods: ofEpochMilli(long) and ofEpochSecond(long)

### ISSUE THREAD

**Issue by kluever** [JodaOrg/joda-time#445]
I realize JodaTime isn't really accepting feature requests these days, but I'd be happy to see a static factory method for `Instant` that took a `long` and had `millis` in the name to avoid the ambiguous constructors.

```java
public static Instant ofEpochMillis(long millis) {
  return new Instant(millis);
}
```

**Comment by ilacorda** [comment]
Hi, I am new to the project and I would like to start contributing to it. Do you follow a specific branch naming convention? If any, I would be happy to be directed to any documentation for contributing to the project. Thank you for your help.

**Comment by jodastephen** [comment]
There is no specific branch naming convention - its your forked repo, so you can choose.

If adding this method, I suggest matching the naming of Java 8 https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html and adding `ofEpochMilli(long)` and `ofEpochSecond(long)` but not ofEpochSecond(long, long)
