### ISSUE TITLE
DateTimeFormatter behavior when Day-of-Month and day-of-week do not match

### ISSUE THREAD

**Issue by minas1** [JodaOrg/joda-time#447]
### Key information

- Joda-Time version: 2.9.7
- Result of `TimeZone.getDefault()`: Europe/Athens
- Result of `DateTimeZone.getDefault()`: Europe/Athens

### Problem description
I am constructing a `DateTimeFormatter` with pattern "EEE MMM dd HH:mm:ss YYYY".
Parsing a string whose day field and day of week field do not match, succeeds, **but an exception could be thrown?**

### Test case
```
@Test
    public void foo() {

        DateTimeFormatter formatter = DateTimeFormat.forPattern("EEE MMM dd HH:mm:ss YYYY");

        // this date is malformed. On the 8th it was Sunday, not Wednesay
        DateTime dateTime = formatter.parseDateTime("Wed Oct 08 08:39:37 2017");
        System.out.println(dateTime.getDayOfMonth()); // prints 4 (Wednesday)
    }
```

**Comment by jodastephen** [comment]
Joda-Time has always leniently parsed this kind of input (day of week does not match day of month). It won't be changing this behaviour now.
