### ISSUE TITLE
Inconsistent timezones returned for abbreviations

### ISSUE THREAD

**Issue by raipc** [JodaOrg/joda-time#449]
joda-time version 2.9.9. JDK 1.8.144

Different time zones are returned for ids EST, MST, HST using different methods (DateTimeZone#forID(id), DateTimeZone#forTimeZone(tz))

### Test case
```java
public static void main(String[] args) {
    String datetime = "2017-09-29T00:00:00.000";
    DateTimeFormatter formatter = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS");
    long tzMillis = formatter.withZone(DateTimeZone.forTimeZone(TimeZone.getTimeZone("EST"))).parseMillis(datetime);
    long idMillis = formatter.withZone(DateTimeZone.forID("EST")).parseMillis(datetime);

    System.out.println("forTimeZone: " + tzMillis);
    System.out.println("forID:       " + idMillis);
}
```

```
forTimeZone: 1506657600000
forID:       1506661200000
```

**Comment by jodastephen** [comment]
These may well be different, but they have been different for 15 years. As such, changing the behaviour now isn't wise. (The Joda-Time method uses the time-zone database, the TimeZone class has even older logic).
