### ISSUE TITLE
NullPointerException when trying to call getYear() from BasicChronology from an object retrieved after serialization

### ISSUE THREAD

**Issue by ahmadzebdeboodi** [JodaOrg/joda-time#453]
I have a LocalDate with a Chronology extending BasicChronology.
I wanted to put it into a Bundle (From Android API) so I serialized it. but after I retrieved the LocalDate object and called getYear(), for some reason the field iYearInfoCache in BasicChronology was null and wasn't regenerated and I got a NullPointerException in the method getYearInfo.

**Comment by jodastephen** [comment]
Android does not implement serialization correctly, so there isn't much we can do.
