### ISSUE TITLE
Performance issue due to usage of synchronized java.util.TimeZone.getTimeZone(String) in CachedDateTimeZone

### ISSUE THREAD

**Issue by akarsh-jain** [JodaOrg/joda-time#457]
Joda-Time Version: v2.3

Since java.util.TimeZone.getTimeZone(String) is synchronized, several concurrent calls to it through org.joda.time.CachedDateTimeZone.toTimeZone() (inherited from org.joda.time.DateTimeZone) get blocked. This creates a performance issue.

This can be rectified by overriding it with the non-synchronized java.util.TimeZone.getTimeZone(ZoneId). Pull request created for the same: #456

**Comment by jodastephen** [comment]
Joda-Time is based on Java SE 5, so there probably isn't much that can be done.
