### ISSUE TITLE
llegalFieldValueException: Cannot parse "29/02/1405" hijri date - Value 29 for dayOfMonth must be in the range [1,28]

### ISSUE THREAD

**Issue by Shivani3832** [JodaOrg/joda-time#459]
Following is my code -
final DateTimeZone SAUDI_ARABIA = DateTimeZone.forID("Asia/Riyadh");
final DateTimeFormatter inputFormat = DateTimeFormat.forPattern( "DD_MM_YYYY").withZone( SAUDI_ARABIA );
String dateOfBirthHijri = "29/02/1405";
final DateTime dateTime = inputFormat.parseDateTime(dateOfBirthHijri); //code burst here
DateTime dateOfBirthHijriObject = dateTime.withChronology( IslamicChronology.getInstance( SAUDI_ARABIA, IslamicChronology.LEAP_YEAR_16_BASED ) );
regionalMap.put("dobHijri", dateOfBirthHijri);

Following error occurs -
org.joda.time.IllegalFieldValueException: Cannot parse "29/02/1405": Value 29 for dayOfMonth must be in the range [1,28]
Please suggest me the solution as early as possible.
If I do not use DateTimeZone and parse simple String to Date then also it is showing error at the same line.
Thanks in advance

**Comment by subodhkarwa** [comment]
Hi @Shivani3832 ,
The snippet you have attached has a clear issue with the pattern you have parsed (DD_MM_YYYY) and the format which you have passed the date (DD/MM/YYYY)

I am not sure, on how are you getting IllegalFieldValueException exception
(Using Java 8, Joda time Version 2.9.9)

This is what is working for me : 
		final DateTimeZone SAUDI_ARABIA = DateTimeZone.forID("Asia/Riyadh");
		final DateTimeFormatter inputFormat = DateTimeFormat.forPattern( "DD/MM/YYYY").withZone( SAUDI_ARABIA );
		String dateOfBirthHijri = "29/02/1405";
		final DateTime dateTime = inputFormat.parseDateTime(dateOfBirthHijri); //code burst here
		DateTime dateOfBirthHijriObject = dateTime.withChronology( IslamicChronology.getInstance( SAUDI_ARABIA, IslamicChronology.LEAP_YEAR_16_BASED ) );
