### ISSUE TITLE
dayOfWeek and months accept different values in Java8 vs. Java9 with local `de`

### ISSUE THREAD

**Issue by s1monw** [JodaOrg/joda-time#462]
I have an issue related to the parsing of date / time patterns with the `de` local. Running on java 8 and below `dayOfWeek` / `month` short names require a to be just the abbreviation but in Java 9 it requires to be suffixed with a `.`. Here is a testcase:

```Java
DateTimeFormatter formatter = DateTimeFormat.forPattern("E, d MMM yyyy HH:mm:ss Z");
FormatDateTimeFormatter dateTimeFormatter = new FormatDateTimeFormatter(
   "E, d MMM yyyy HH:mm:ss Z", formatter.withZone(DateTimeZone.UTC), Locale.ROOT);
FormatDateTimeFormatter f = new FormatDateTimeFormatter(dateTimeFormatter.format(),
            dateTimeFormatter.parser(), dateTimeFormatter.printer(),  Locale.GERMAN);
f.parser().parseMillis("Mi., 06 Dez. 2000 02:55:00 -0800"); // works with java9
f.parser().parseMillis("Mi, 06 Dez 2000 02:55:00 -0800"); // works with java8
```

It feels to me that the underlying bundle used to access these local dependent names for the day [here](https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/format/DateTimeFormatterBuilder.java#L1739) I don't know if any other locals are broken but I can help testing. I can also help fixing it but I am not sure if you wanna fix it in the first place. I also don't think special-casing is the right thing here unless it's the only thing that is broken.

**Comment by s1monw** [comment]
just to shed some light on where it's coming from:

```Java
DateFormatSymbols s = new DateFormatSymbols(Locale.GERMAN);
System.out.println(Arrays.toString(s.getShortWeekdays()));
```


will print `[, So., Mo., Di., Mi., Do., Fr., Sa.]` on Java 9.0.1 but on java 1.8.0_131 it will print `[, So, Mo, Di, Mi, Do, Fr, Sa]` so I think that is actually a BWC break in the JDK.

**Comment by s1monw** [comment]
for the record: I emailed the jdk i18n-dev list [here](http://mail.openjdk.java.net/pipermail/i18n-dev/2017-December/002426.html)

**Comment by jodastephen** [comment]
As per the reply on the JDK list, the data has changed, and it can change between releases anyway.
