### ISSUE TITLE
Duration.isShorterThan() doesn't work fine with opposite durations. 

### ISSUE THREAD

**Issue by zimnyx** [JodaOrg/joda-time#465]
Hi!
I've recently discovered an issue with Duration comparing, please see details below.

### Key information

- Joda-Time version: 2.9.9 (current master)
- Result of `TimeZone.getDefault()`: ```sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.Simple
TimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1
,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]```
- Result of `DateTimeZone.getDefault()`: Europe/London

### Problem description
When comparing Duration length using isShorterThan/isLongerThan, Joda does take into consideration direction of Duration (start vs end time order) and results of such comparisons are not correct. Please see unit test example.
 
### Test case
```
    public void testDurationLengthComparing() {
        // Let's have 3s duration
        Duration u = Duration.standardSeconds(3);
        // 10s duration, one direction
        Duration d1 = new Duration(DateTime.now().minus(Duration.standardSeconds(10)), DateTime.now());
        // 10s again, opposite direction
        Duration d2 = new Duration(DateTime.now(), DateTime.now().minus(Duration.standardSeconds(10)));

        // This one passes and it's perfectly fine
        assertEquals(true, d1.isLongerThan(u));

        // This test fails, which is pretty surprising. I think, Joda should either:
        // * use absolute length of duration for comparing: Math.abs(Duration.getMillis())
        // * or throw exception when comparing durations with opposite direction via isShorterThan/isLongerThan
        assertEquals(true, d2.isLongerThan(u));
    }
```

**Comment by jodastephen** [comment]
I see how it looks odd, but this has been in Joda-Time for 15 years so I think changing it at this stage would be not be the best choice.

**Comment by zimnyx** [comment]
Hi Stephen! Problem with this method is that if someone has not studied its sources, he will assume comparison works per absolute length, and unless his code is well unit-tested, he is in trouble. The backwards-compatible approach would be to add logger.warn("Comparing Duration objects with opposite direction, yelds unexpected results.") plus update documentation too.
I can submit a patch, just let me know if you would accept it. Thanks.

**Comment by jodastephen** [comment]
Low level libraries don't log. I'm afraid the behaviour is staying as is. A PR to clarify documentation might be accepted.

**Comment by zimnyx** [comment]
Added pull request: https://github.com/JodaOrg/joda-time/pull/467

**Comment by zimnyx** [comment]
@jodastephen Please see the pull request.
