### ISSUE TITLE
Supported timezone documentation - Javadoc inconsistent with website; Javadoc inconsistent with behavior

### ISSUE THREAD

**Issue by jacospain** [JodaOrg/joda-time#475]
### Key information

- Joda-Time version: 2.9.9
- Result of `TimeZone.getDefault()`: sun.util.calendar.ZoneInfo[id="America/Chicago",offset=-21600000,dstSavings=3600000,useDaylight=true,transitions=235,lastRule=java.util.SimpleTimeZone[id=America/Chicago,offset=-21600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]]
- Result of `DateTimeZone.getDefault()`:America/Chicago

### Problem description
The Javadoc says explicitly that EST is not accepted by DateTimeZone:

http://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeZone.html

"Thus EST and ECT are not accepted."

However, this other documentation page that is linked directly from the main Joda-Time page:

http://www.joda.org/joda-time/timezones.html

lists EST as supported, and indeed EST works with the forID factory method

### Test cases

DateTimeZone.forID("EST")
> EST

DateTimeZone.forID("ECT")
> throws IllegalArgumentException

**Comment by jodastephen** [comment]
The IANA time zone database includes EST, MST and HST but not PST. I've clarified the Javadoc
