### ISSUE TITLE
Java 11 Compatibility check

### ISSUE THREAD

**Issue by abernatptc** [JodaOrg/joda-time#480]
Hi,
We are reaching out to you to check Java 11 compatibility of the library: joda-time.

Could you help us by answering the following questions:
1.    Is the library compatible with Java 11 ? (Y/N)
2.    Is the library supported with Java 11? (Y/N)
3.    (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
4.    Date of support availability?

Thanks,
Albert Bernat 
PTC

**Comment by mrjink** [comment]
Please be advised that [the home page](http://www.joda.org/joda-time/) states:

> The standard date and time classes prior to Java SE 8 are poor. By tackling this problem head-on, Joda-Time became the de facto standard date and time library for Java prior to Java SE 8. **Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.**

(Emphasis from that page, not mine.)

**Comment by jodastephen** [comment]
Spamming multiple open source projects with the same question is not appropriate behaviour for a company. Open source does not have "support". Its up to users to try the code, see if it works and report issues. Please cease and desist your spamming.
