### ISSUE TITLE
Turkey's DST has some problems

### ISSUE THREAD

**Issue by o0rid0o** [JodaOrg/joda-time#489]
### Key information

- Joda-Time version
2.10.1
- Result of `TimeZone.getDefault()`
sun.util.calendar.ZoneInfo[id="Asia/Shanghai",offset=28800000,dstSavings=0,useDaylight=false,transitions=19,lastRule=null]
- Result of `DateTimeZone.getDefault()`
Asia/Shanghai
### Problem description
Turkey's decision to permanently remain on UTC+3
vi {tzdata2018g}/europe: 

`# From Paul Eggert (2017-11-08):`
`# Although Google Translate misfires on that source, it looks like`
`# Turkey reversed last month's decision, and so will stay at +03.`

`# Zone  NAME            GMTOFF  RULES   FORMAT  [UNTIL]`
`Zone    Europe/Istanbul 1:55:52 -       LMT     1880`
`                       1:56:56 -       IMT     1910 Oct # Istanbul Mean Time?`
`                        2:00    Turkey  EE%sT   1978 Oct 15`
`                        3:00    Turkey  +03/+04 1985 Apr 20`
`                        2:00    Turkey  EE%sT   2007`
`                        2:00    EU      EE%sT   2011 Mar 27  1:00u`
`                        2:00    -       EET     2011 Mar 28  1:00u`
`                        2:00    EU      EE%sT   2014 Mar 30  1:00u`
`                        2:00    -       EET     2014 Mar 31  1:00u`
`                        2:00    EU      EE%sT   2015 Oct 25  1:00u`
`                        2:00    1:00    EEST    2015 Nov  8  1:00u`
`                        2:00    EU      EE%sT   2016 Sep  7`
`                        3:00    -       +03`
`Link    Europe/Istanbul Asia/Istanbul   # Istanbul is in both continents.`

But can't get the correct result

### Test case
java code: 
`DateTime date1_sh = new DateTime(2018, 10, 28, 8, 0, 0, 0, DateTimeZone.forID("Asia/Shanghai"));`
`DateTime date2_sh = new DateTime(2018, 10, 28, 9, 0, 0, 0, DateTimeZone.forID("Asia/Shanghai"));`
`System.out.println("Asia/Shanghai 1: " + date1_sh.toString("yyyy-MM-dd HH:mm:ss.SSS Z"));`
`System.out.println("Asia/Shanghai 2: " + date2_sh.toString("yyyy-MM-dd HH:mm:ss.SSS Z"));`
`System.out.println("Europe/Istanbul 1: " + date1_sh.withZone(DateTimeZone.forID("Europe/Istanbul")).toString("yyyy-MM-dd HH:mm:ss.SSS Z"));`
`System.out.println("Europe/Istanbul 2: " + date2_sh.withZone(DateTimeZone.forID("Europe/Istanbul")).toString("yyyy-MM-dd HH:mm:ss.SSS Z"));`

output:
`Asia/Shanghai 1: 2018-10-28 08:00:00.000 +0800`
`Asia/Shanghai 2: 2018-10-28 09:00:00.000 +0800`
`Europe/Istanbul 1: 2018-10-28 03:00:00.000 +0300`
`Europe/Istanbul 2: 2018-10-28 03:00:00.000 +0200`

**Comment by jodastephen** [comment]
I assume you are not running the version of Joda-Time you think you are. I can't reproduce you tests - everything works fine for me ;-)

**Comment by o0rid0o** [comment]
Thank you for your reply
Another jar file contains an old version
After the problematic jar is recompiled and packaged, the problem has been solved.
