### ISSUE TITLE
Cannot create a DateTime from Hijri date

### ISSUE THREAD

**Issue by jalil1408** [JodaOrg/joda-time#490]
for the Hijri date 1440-02-30 I tried:

DateTime date = new DateTime(1440, 2, 30, 0, 0, IslamicChronology.getInstance());
return date.plusDays(2).toString("yyyy-MM-dd");

I got: org.joda.time.IllegalFieldValueException: Value 30 for dayOfMonth must be in the range [1,29]

How can I add days to a given Hijri date?

**Comment by jodastephen** [comment]
The Javadoc for the chronology says "The tabular form of the calendar defines 12 months of alternately 30 and 29 days". Since the month is 2, the length of the month is 29 days. Months 1 and 3 would be 30 days long.

To add 2 days to a valid date, use `DateTime.plusDays(2)`.
