### ISSUE TITLE
Update to tzdb 2018h

### ISSUE THREAD

**Issue by janbolat** [JodaOrg/joda-time#493]
Any plans to update to 2018h? 

Thank you

**Comment by janbolat** [comment]
@jodastephen any plans on an update to 2018h?

**Comment by jodastephen** [comment]
In general, I don't produce a new release for every tzdb release, as developers can [release their own](https://www.joda.org/joda-time/tz_update.html).

**Comment by janbolat** [comment]
@jodastephen Thank you for clarification.
@dlew Thanks
