### ISSUE TITLE
PrecalculatedZone - iTransitions contains incorrect value 

### ISSUE THREAD

**Issue by infoShare** [JodaOrg/joda-time#494]
### Key information
- Joda-Time version
**2.10.1**
- Result of `TimeZone.getDefault()`
**sun.util.calendar.ZoneInfo[id="Europe/Belgrade",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=119,lastRule=java.util.SimpleTimeZone[id=Europe/Belgrade,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]**
- Result of `DateTimeZone.getDefault()`
**UTC**

### Problem description

Offset is selected incorrectly for PrecalculatedZone.
iTransitions contains wrong value (for below test case)

iTransitions = {long[3]@751} 
 0 = -9223372036854775808
 1 = 947030400000 (2000-01-05T00:00:00.000Z)
 2 = 947196000000 (**2000-01-06T22:00:00.000Z**)

### Test case (for TestBuilder)

    public void testPrecalculatedZoneOffsets() throws IOException {
        DateTime minimumDate = new DateTime(1, 1, 1, 0, 0, 0, originalDateTimeZone);

        DateTime firstDate = new DateTime(2000, 1, 5, 0, 0, 0, originalDateTimeZone);
        DateTime secondDate = firstDate.plusDays(2);
        int OFFSET = 120 * MILLIS_PER_MINUTE;
        DateTimeZoneBuilder builder = new DateTimeZoneBuilder()
                .setStandardOffset(0)
                .addRecurringSavings("Offset initializing DST rule " + minimumDate.toString(), 0,
                        minimumDate.getYear(), minimumDate.getYear(), 'w', 1, 1, 0, false, minimumDate.getMillisOfDay())
                .addCutover(firstDate.getYear(), 'w', firstDate.getMonthOfYear(), firstDate.getDayOfMonth(), 0, false, firstDate.getMillisOfDay())
                .setStandardOffset(OFFSET)
                .addRecurringSavings("Offset initializing DST rule " + firstDate.toString(),
                        0, firstDate.getYear(),
                        firstDate.getYear(), 'w', firstDate.getMonthOfYear(),
                        firstDate.getDayOfMonth(), 0, false, 0)
                .addCutover(secondDate.getYear(), 'w', secondDate.getMonthOfYear(), secondDate.getDayOfMonth(), 0, false, secondDate.getMillisOfDay())
                .setStandardOffset(0)
                .addRecurringSavings("Offset initializing DST rule " + secondDate.toString(),
                        0, secondDate.getYear(),
                        secondDate.getYear(), 'w', secondDate.getMonthOfYear(),
                        secondDate.getDayOfMonth(), 0, false, 0);

        DateTimeZone dateTimeZone = builder.toDateTimeZone("ID", false);

        //Failing assertion
        assertEquals(OFFSET, dateTimeZone.getOffset(secondDate.minusMinutes(1)));

        assertEquals(OFFSET, dateTimeZone.getOffset(secondDate.minusDays(1)));
        assertEquals(0, dateTimeZone.getOffset(secondDate.plusDays(1)));
    }

**Comment by jodastephen** [comment]
I assume that your goal is to try and use the `DateTimeZoneBuilder` API to create your own time zone. This is an unusual goal, as that API is normally only used by the IANA parser, and is closely tied to that data format.

It is likely that the set of calls you are making to the API is wrong. Its really complex, and was written over 15 years ago. What I can say is that in most cases, the standard offset stays the same for a time zone - only rarely does it change. The DST changes are handled by `addRecurringSavings` in the second parameter (which this code does not do). I'd expect the pattern to be one call to `setStandardOffset`, two calls to `addRecurringSavings` (into and out of DST each year, one with a `saveMillis` of zero and one with a `saveMillis` of 1 hour) and one call to `addCutover` to start the process.

Hope that helps your investigation.
