### ISSUE TITLE
NPE in Minutes.minutesBetween

### ISSUE THREAD

**Issue by pranavbhole** [JodaOrg/joda-time#498]
Minutes minutes = Minutes.minutesBetween(eventTime, new DateTime());
where eventTime is joda  DateTime object. 
java.lang.NullPointerException: null
	at org.joda.time.base.BaseSingleFieldPeriod.between(BaseSingleFieldPeriod.java:72)
	at org.joda.time.Minutes.minutesBetween(Minutes.java:101)

**Comment by jodastephen** [comment]
Can you specify the inputs in full please.

**Comment by jodastephen** [comment]
Closing as no further info provided and a basic test of the functionality works OK.
