### ISSUE TITLE
Interval.toDuration().toStandardDays().getDays() result differ for 2019-02-14 vs. 2019-02-15

### ISSUE THREAD

**Issue by dlehammer** [JodaOrg/joda-time#499]
### Key information

- Joda-Time version
```
2.10.1
```

- Result of `TimeZone.getDefault()`
```
Europe/Copenhagen
```

- Result of `DateTimeZone.getDefault()`
```
sun.util.calendar.ZoneInfo[id="Europe/Copenhagen",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=133,lastRule=java.util.SimpleTimeZone[id=Europe/Copenhagen,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
```

### Problem description

`Interval.toDuration().toStandardDays().getDays()` result differ for 2019-02-14 vs. 2019-02-15.

The symptom was discovered by a continous integration test-case evaluating deadline-logic nightly.

The test-case is straigthforward
1. create 2 `LocalDate`
```
LocalDate date1 = LocalDate.now()
LocalDate date2 = date1.plusDays(45)
```
2. verify that the deadline-logic also detects 45 days between `date1` and `date2`
And from 2019-02-15 and onwards the test-case has been failing consistently, with 44 days instead.

Below is a screenshot from a Gradle module demonstrating the symptom: 
![screenshot from 2019-02-18 16-50-05](https://user-images.githubusercontent.com/17439718/52963047-15332200-339f-11e9-8cff-71a567e5832f.png)

Reverting to an earlier input date produces the expected results... :)

Symptom discovered for Joda-Time v2.9.9, but is still present in v2.10.1.
Symptom discovered on `OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)` and is still present for `OpenJDK Runtime Environment (build 1.8.0_201-b09)`

### Test case
I've created small Gradle module demonstrating the symptom.

1. clone [repo](https://github.com/dlehammer/joda-time-issues-499).
```
$ git clone git@github.com:dlehammer/joda-time-issues-499.git
```

2. execute test-suite
```
$ cd joda-time-issues-499
[joda-time-issues-499]$ ./gradlew check
```
3. evaluate test-suite result:
```
:test

support.util.DateUtilSpec > get number of days - date1: 2019-02-15, date2: 2019-04-01, expected: 45 days FAILED
    org.spockframework.runtime.SpockComparisonFailure at DateUtilSpec.groovy:15

support.util.DateUtilSpec > get number of days - date1: 2019-02-16, date2: 2019-04-02, expected: 45 days FAILED
    org.spockframework.runtime.SpockComparisonFailure at DateUtilSpec.groovy:15

support.util.DateUtilSpec > get number of days - date1: 2019-02-17, date2: 2019-04-03, expected: 45 days FAILED
    org.spockframework.runtime.SpockComparisonFailure at DateUtilSpec.groovy:15

support.util.DateUtilSpec > get number of days - date1: 2019-02-18, date2: 2019-04-04, expected: 45 days FAILED
    org.spockframework.runtime.SpockComparisonFailure at DateUtilSpec.groovy:15

10 tests completed, 4 failed
:test FAILED
```

**Comment by dlehammer** [comment]
The deadline-logic responsible for getting the number of days can be found [here](https://github.com/dlehammer/joda-time-issues-499/blob/master/src/main/groovy/support/util/DateUtil.groovy#L11).

**Comment by jodastephen** [comment]
Your code is adding 45 *logical* days using `LocalDate.plusDays(45)`. You are then calculating an interval using instants using `date.toDate().getTime()`. Finally, you convert back to days using *standard* `interval.toDuration().toStandardDays().getDays()`.

The issue occurs when you reach the DST cutover date at the end of March. Up until that date a logical day is always 24 hours long. However, 2019-03-31 is only 23 hours long. So, once your calculationsgo beyond that date, the number of days is one less because you haven't reached a full 24 hour day.

To fix your code, avoid mixing logical and standard days.

    static int getNumberOfDays(LocalDate date1, LocalDate date2) {
        return Math.abs(Days.daysBetween(date1, date2).getDays());
    }

Moreover, any code like `date1.toDate().getTime()` that uses `toDate()` is dubious as it uses the JDK `Date` class. Use `date1.toDateTimeAtStartOfDay()` would be better.

**Comment by dlehammer** [comment]
Thanks alot @jodastephen!

For both the detailed explanation of the symptom and suggested best practice for retrieving the number of logical days.

I've added the suggested fix to the [repo](https://github.com/dlehammer/joda-time-issues-499/commit/538f9293440bdab0303226c4c2ebebabcc1ed7d2) for future reference.

It's quite the gotcha, as I didn't spot the use of `StandardDays` vs `days` (implicit logical).
I haven't been able to locate the described distinction between "days" in the `joda-time` source og via Google.

Perhaps the Javadoc for `StandardDays` could include a warning for future reference :)

**Comment by jodastephen** [comment]
It already says this, which is pretty comprehensive.

> Converts this duration to a period in days assuming that there are the standard number of milliseconds in a day.
>This method assumes that there are 24 hours in a day,
> 60 minutes in an hour, 60 seconds in a minute and 1000 milliseconds in
> a second. This will be true for most days, however days with Daylight
> Savings changes will not have 24 hours, so use this method with care.
