### ISSUE TITLE
Time format is changing for UTC

### ISSUE THREAD

**Issue by raviraj92** [JodaOrg/joda-time#500]
Hi Team,

### Key information

- Joda-Time version
2.9.9

### Problem description
I am trying to pass the UTC time like this "2019-01-31T00:00:00.010+00:00" and I am getting "2019-01-31T00:00:00Z".  Here offset "00:00" getting replaced with "Z". I know its equal.  But is there any possibility to return the same date time without parsing or removing "00:00".

### Test case
org.joda.time.DateTime dateTime2 = org.joda.time.DateTime.parse("2019-01-31T00:00:00.010+00:00");
System.out.println("Date Time 2: " + dateTime2);

Output coming:
Date Time 2: 2019-01-31T00:00:00.010Z

Output Expecting: 
Date Time 2: 2019-01-31T00:00:00.010+00:00

Thanks for all your great work and support.

**Comment by jodastephen** [comment]
You have to use `DateTimeFormatterBuilder` and use `appendTimeZoneOffset("+00:00", "+00:00", true, 2, 3)` to control the format of the offset.
