### ISSUE TITLE
Europe/Minsk timezone is incorrect

### ISSUE THREAD

**Issue by Pupkur** [JodaOrg/joda-time#506]
Now

+02:00 | Europe/Minsk -- | --

Must be
+03:00 | Europe/Minsk -- | --

https://en.wikipedia.org/wiki/Minsk

**Comment by jodastephen** [comment]
I'm guessing you are using an old version of Joda-Time? What version are you using, and can you upgrade?

**Comment by Pupkur** [comment]
http://joda-time.sourceforge.net/timezones.html

**Comment by jodastephen** [comment]
That website hasn't been updated in years. The current page is https://www.joda.org/joda-time/timezones.html - I tried [raising a PR](https://github.com/logstash-plugins/logstash-filter-date/pull/132).

**Comment by Pupkur** [comment]
Thanks!
