### ISSUE TITLE
Exception Thrown When Parsing String to DateTime Using DateTimeFormatter

### ISSUE THREAD

**Issue by nadirw91** [JodaOrg/joda-time#507]
### Key information

- Joda-Time version 2.10.2
- Result of `DateTimeFormatter formatter.parseDateTime`

### Problem description
I have some code that parses a String to a date time with the format of "MM/yyyy". This works perfectly fine except for when the Timezone is set to "Asia/Amman" and the format of the string is "4/2022" or "04/2022". Any other combination of months and year works just fine. 

Illegal State Exception
Message: Cannot parse "4/2022": Illegal instant due to time zone offset transition (Asia/Amman)

### Test case
 DateTimeFormatter formatter = DateTimeFormat.forPattern( "MM/yyyy" ).withZone( 
DateTimeZone.forID( "Asia/Amman" ) ).withLocale( Locale.US );

DateTime cardExpirationMonth = formatter.parseDateTime( 4 + "/" + 2022 );

**Comment by jodastephen** [comment]
This issue will occur because midnight 00:00 did not exist on that date in that time-zone. This is a general problem with Joda-Time -the best solution is to move to Java 8 and java.time.*.
