### ISSUE TITLE
ISODateTimeFormat.forFields parser doesn't work when using not extended

### ISSUE THREAD

**Issue by Lanboost** [JodaOrg/joda-time#513]
### Key information

- Joda-Time version
2.10.3
- Result of `TimeZone.getDefault()`
`sun.util.calendar.ZoneInfo[id="Europe/Stockholm",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=119,lastRule=java.util.SimpleTimeZone[id=Europe/Stockholm,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]`
- Result of `DateTimeZone.getDefault()`
Europe/Stockholm

### Problem description
ISODateTimeFormat.forFields generates a broken parser when using extended = false

### Test case
Java
```java

import org.joda.time.DateTimeFieldType;
import org.joda.time.Instant;
import org.joda.time.format.ISODateTimeFormat;

public class Test {

    public static void main(String[] args) {
        java.util.ArrayList<DateTimeFieldType> test = new java.util.ArrayList();
        test.add(DateTimeFieldType.year());
        test.add(DateTimeFieldType.monthOfYear());
        test.add(DateTimeFieldType.dayOfMonth());

        Instant.parse("20050330", ISODateTimeFormat.forFields(test, false, true));
    }
}

```
Output:
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid format: "20050330" is too short
```

Scala
```scala
"test" should "Not break" in {
    import collection.JavaConverters._
    val form = ISODateTimeFormat
      .forFields(
        Seq(
          DateTimeFieldType.year(),
          DateTimeFieldType.monthOfYear(),
          DateTimeFieldType.dayOfMonth()).asJavaCollection,
        false,
        true)
      .withZoneUTC()
    Instant.parse(
      "20050320",
      form
    )
  }
```

**Comment by jodastephen** [comment]
The `forFields()` method was intended for formatting, not parsing. I suspect it works fine for most extended formats, just not the basic format ones.

I've added additional Javadoc to clarify this.
