### ISSUE TITLE
DateTime.parse doesn't seem to parse YYYYMMDD correctly.

### ISSUE THREAD

**Issue by szabado** [JodaOrg/joda-time#515]
### Key information

ISO-8601 specifies (at least according to [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601), I don't have access to the actual ISO) that `YYYYMMDD` is a valid way to specify a calendar date.

- Joda-Time version: 2.10.4
- Result of `TimeZone.getDefault()`: `sun.util.calendar.ZoneInfo[id="America/Toronto",offset=-18000000,dstSavings=3600000,useDaylight=true,transitions=231,lastRule=java.util.SimpleTimeZone[id=America/Toronto,offset=-18000000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]]`
- Result of `DateTimeZone.getDefault()`: `America/Toronto`

### Problem description

The DateTime.parse() method, which I expect to be ISO-8601 compliant, doesn't seem to actually comply to the standard in this one particular case? Passing in `20190101` doesn't parse as January 1st, 2019, but rather January 1st, 20190101.

I looked at the specification for `ISODateTimeFormat.dateTimeParser()` and I saw that this format is not supported according to the documentation. This popped up as a bug for me, and I feel like the documentation could be more clear, if this is indeed the intentional behaviour?

### Test case

```import org.joda.time.DateTime;

import static org.junit.Assert.assertEquals;

public class Test {
  @org.junit.Test
  public void TestCase() {
    assertEquals(DateTime.parse("20190101"), DateTime.parse("2019-01-01"));
  }
}
```

**Comment by jodastephen** [comment]
The ISO-8601 standard is quite large and has a variety of formats.

The `DateTime.parse()` method accepts the most common one, which is `yyyy-MM-dd`. The linked documentation fully spells out the input that is accepted.

As such, everything is working as expected here. Thanks

**Comment by szabado** [comment]
My main issue is it makes it very hard to avoid leaky abstractions with this library? You can no longer specify that you accept the ISO-8601 format, you have to specify that you accept the subset accepted by this library.

Not a huge pain, just wanted to say my two bits. Given this library is more in a maintenance state it makes sense to maintain the current behaviour.
