### ISSUE TITLE
Time zones Etc/UTC and UTC are not considered equal

### ISSUE THREAD

**Issue by GitoMat** [JodaOrg/joda-time#518]
### Key information
- Joda-Time version 2.10.5

### Problem description
According to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones UTC is an alias for Etc/UTC, still the code snippet below returns false. The problem is that DateTimeZone.forID("UTC") is of type UTCDateTimeZone while DateTimeZone.forID("Etc/UTC") is of type FixedDateTimeZone, so the check "obj instanceof UTCDateTimeZone" in the equals method fails.
The same applies to the deprecated time zones Etc/Universal, Etc/Zulu, Universal, Zulu and maybe others.

### Test case
DateTimeZone.forID("UTC").equals(DateTimeZone.forID("Etc/UTC"))

**Comment by jodastephen** [comment]
The name of a time-zone is a key piece of information about the time-zone, and is thus compared in the equals method. In JSR-310 `java.time.*` there is a `normalize` method that removes the distinction. You could write a utility method to do the same for Joda-Time - comparing the offsets to see if two zones produce the same output.

**Comment by GitoMat** [comment]
Thank you for the response, you can consider this resolved. The problem I encountered is that the default time zone of Jackson is set as "UTC", while the Debian/OpenJDK Docker image default is "Etc/UTC". So equals for the same DateTime when it was once deserialized with Jackson and once created otherwise returned false.
I agree tough that time zone ids should not be treated equal and I should have used the DateTime.isEqual method in the first place.
I understand "Etc/UTC" is technically the canonical name, but most people would just use "UTC". If those defaults differ in different parts of the system the resulting behaviour can be unexpected ...
