### ISSUE TITLE
Problem Daylight Saving Time

### ISSUE THREAD

**Issue by alexvieirasj** [JodaOrg/joda-time#519]
**Key information**
Joda-Time version 2.10.5

**Problem description**
I have a problem when I try to convert dates as from November 03, 2019 it returns 1 hour behind. My TimeZone is "America/Sao_Paulo" and in Brazil this year haven't Daylight Saving Time.

**Test case**
 DateFormat df = new SimpleDateFormat ("dd/MM/yyyy HH:mm:ss");
 String dateString = "03/11/2019 08:30:00";
 Date dateObject = df.parse(dateString); 
 DateTime dt = new DateTime(dateObject);
 System.out.println(dt); //return: 2019-11-03T07:30:00.000-03:00

**Comment by cesguerra** [comment]
The same problem is happening here =/

**Comment by cesguerra** [comment]
To solve the problem download tzupdate.jar:
https://www.oracle.com/technetwork/java/javase/downloads/tzupdater-download-513681.html

Run as root:
java -jar tzupdater.jar -f

**Comment by dmisen** [comment]
JDK8 prior 1.8.0_231 has incorrect time handling for Brasil as well as Joda time library prior 2.10.3:

Joda2.10.2 + JDK 1.8.0_152:
```
JDK:
Current time is 2019-11-08 at 09:12:17 BRST
JODA:
Joda LocalDateTime - 2019-11-08T09:12:17.441
```

Joda2.10.3 + JDK 1.8.0_152:
```
JDK:
Current time is 2019-11-08 at 09:12:17 BRST
JODA:
Joda LocalDateTime - 2019-11-08T09:12:17.441
```

Joda2.10.2 + JDK 1.8.0_231:
```
JDK:
Current time is 2019-11-08 at 08:16:45 BRT
JODA:
Joda LocalDateTime - 2019-11-08T09:16:45.502
```

Joda2.10.3 + JDK 1.8.0_231
```
JDK:
Current time is 2019-11-08 at 08:17:03 BRT
JODA:
Joda LocalDateTime - 2019-11-08T08:17:03.033
JDK1.8._152 can be fixed by executing "java -jar tzupdater.jar -f" as a root.
```

Using tzupdate.jar for JDK does not solve the issue for joda-time, but joda-time 2.10.3 has no this issue.

**Comment by jodastephen** [comment]
To have the latest data from tzdb, please update to the latest version of Joda-Time.
