### ISSUE TITLE
Nanosecond precision

### ISSUE THREAD

**Issue by eregon** [JodaOrg/joda-time#52]
Hello,

In JRuby, we want nanosecond precision in a couple places.

The JVM only provides a millisecond precision wall-clock (but that should change with JSR 310). So of course for now we can only retain nanoseconds that are given by the user.

The logic to handle nanoseconds lives in RubyTime, the class for handling Ruby "Time" objects. I would like to extract it to some DateTime-like class handling nanoseconds (that is an additional int field). DateTime is a final class so it cannot be subclassed. Composition is of course possible but it might hurt a bit performance and it means to write every delegation method.

What would be a good way to add support for nanosecond precision to DateTime according to you?
Do you have plans for doing this in Joda-Time?

**Comment by bjfish** [comment]
@eregon Would this backport project work for nanosecond precision: https://github.com/ThreeTen/threetenbp ?

**Comment by eregon** [comment]
@bjfish Yeah, it seems that would work! The API differs (different class names for instance), so adapting might take some time, as well as integrating with existing Ruby Time/Date implementations keeping nanos separately.
