### ISSUE TITLE
Duplicate class org.joda.time.Chronology 

### ISSUE THREAD

**Issue by mdaslamHossin** [JodaOrg/joda-time#527]
Duplicate class org.joda.time.tz.DateTimeZoneBuilder found in modules jetified-joda-time-2.10.3-no-tzdb-no-tzdb.jar (joda-time:joda-time:2.10.3) and jetified-joda-time-2.10.3.jar (joda-time:joda-time:2.10.3)

**Comment by jodastephen** [comment]
These "jetified" jar files are not produced by joda-time, so they are not something I can help with.
