### ISSUE TITLE
java.lang.IllegalArgumentException: The datetime zone id 'IST' is not recognised

### ISSUE THREAD

**Issue by dis70** [JodaOrg/joda-time#528]
Hello

We get this error
java.lang.IllegalArgumentException: The datetime zone id 'IST' is not recognised (India Standard Time).
I listed all timezones in Joda (2.10.5) and found that IST is not available.

Is there a plan to support IST?

Thank you
Best regards
Dieter

**Comment by jodastephen** [comment]
For "IST" you can use "Asia/Kolkata"

**Comment by yadav-hemant** [comment]
Even "Asia/Kolkata" is also not supported

**Comment by ayushman1024** [comment]
Asia/Kolkata is supported
