### ISSUE TITLE
"TZDB check" Workflow failing since tzdb 2020b

### ISSUE THREAD

**Issue by garychappell** [JodaOrg/joda-time#541]
"TZDB check" Workflow failing since tzdb 2020b. Looks like it's due to [a line in the workflow that copies a file named pacificnew from eggert/tz](https://github.com/JodaOrg/joda-time/blob/d4a2c3133a4929af618f38c8bb70f4117b602c79/.github/workflows/tzdbupdate.yml#L73), but that file is no longer present since 2020b.

Thanks,
Gary

**Comment by garychappell** [comment]
BTW, systemv was also removed from eggert/tz with the 2020b release so line 75 in the TZ check workflow should also be removed.

**Comment by jodastephen** [comment]
Yep. Was going to fix this anyway. Should hopefully resolve now on Wednesday.
