### ISSUE TITLE
isLocalDateTimeGap() doesn't wok as expected in version 2.10.9

### ISSUE THREAD

**Issue by grzesiek2010** [JodaOrg/joda-time#555]
### Key information
- Joda-Time version 2.10.9

### Problem description
Hi!
I'm a developer working on [GetODK](https://github.com/getodk/collect), an open-source project used for collecting data.
We use [joda time android](https://github.com/dlew/joda-time-android) which is a wrapper around this project and I just wanted to update our dependency to the newest version (which uses joda-time:2.10.9). However, I noticed a problem with date gaps.
This library contains a method [isLocalDateTimeGap](https://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeZone.html#isLocalDateTimeGap-org.joda.time.LocalDateTime-) and we use it to make sure that during selecting dates our users won't be allowed to pass a value that didn't exist.
This is our method responsible for that:

```java
    public static LocalDateTime skipDaylightSavingGapIfExists(LocalDateTime date) {
        final DateTimeZone dtz = DateTimeZone.getDefault();

        if (dtz != null) {
            while (dtz.isLocalDateTimeGap(date)) {
                date = date.plusMinutes(1);
            }
        }
        return date;
    }
```

and we also have a test:

```java

    @Test
    public void skipDaylightSavingGapIfExistsTest() {
        DateTimeZone originalDefaultTimeZone = DateTimeZone.getDefault();
        DateTimeZone.setDefault(DateTimeZone.forID("Africa/Nairobi"));

        // 1 Jan 1960 at 00:00:00 clocks were turned forward to 00:15:00
        LocalDateTime ldtOriginal = new LocalDateTime().withYear(1960).withMonthOfYear(1).withDayOfMonth(1).withHourOfDay(0).withMinuteOfHour(0).withSecondOfMinute(0).withMillisOfSecond(0);
        LocalDateTime ldtExpected = new LocalDateTime().withYear(1960).withMonthOfYear(1).withDayOfMonth(1).withHourOfDay(0).withMinuteOfHour(15).withSecondOfMinute(0).withMillisOfSecond(0);

        assertEquals(ldtExpected, DateTimeUtils.skipDaylightSavingGapIfExists(ldtOriginal));
        DateTimeZone.setDefault(originalDefaultTimeZone);
    }
```

everything worked well before upgrading (when we used 2.10.8) but now that gap is not skipped. 
The problem is that` isLocalDateTimeGap(date)` no longer returns true for that time zone and date but it should: https://www.timeanddate.com/time/change/kenya/nairobi?year=1960

I also tried another gap and it worked well. Is that because the one I used and described above isn't really a DST change (they just changed their timezone I guess)? If so how should we handle such cases now?

**Comment by jodastephen** [comment]
The time zone of Kenya has been changes to be more accurate, timanddate.com is wrong
https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/tz/src/africa#L486-L545
