### ISSUE TITLE
Wrong TimeZone from "Africa/Ceuta" coords using  TimezoneMapper.latLngToTimezoneString

### ISSUE THREAD

**Issue by jferre-spec** [JodaOrg/joda-time#557]
- Joda-Time version
- 'joda-time:joda-time:2.10.10'
- 
assertEquals("Africa/Ceuta",TimezoneMapper.latLngToTimezoneString(35.89169697015598, -5.300627411338721));
-Result:

org.junit.ComparisonFailure: 
Expected:Africa/Ceuta
Actual:Africa/Casablanca

### Problem description
Ceuta/Melilla uses Africa/Ceuta TimeZone but TimezoneMapper.latLngToTimezoneString returns Africa/Casablanca using Ceuta coordinates (35.89169697015598, -5.300627411338721).

### Test case
assertEquals("Africa/Ceuta",TimezoneMapper.latLngToTimezoneString(35.89169697015598, -5.300627411338721));

**Comment by jodastephen** [comment]
`TimezoneMapper` is not part of Joda-Time.
