### ISSUE TITLE
Release history date for release 2.10.10 invalid - 2020-02-05 should be 2021-02-05

### ISSUE THREAD

**Issue by mbjarland** [JodaOrg/joda-time#559]
### Key information

- Go to the current joda time web site, release history page. The latest release has an invalid release date.

### Problem description

The title of the issue describes the issue. Attaching screen. 

### Test case

Go to the site, click Releases > Release Notes in the top nav.

![Screenshot from 2021-04-22 10-55-29](https://user-images.githubusercontent.com/58158/115686779-da035380-a359-11eb-84de-8ab17758e389.png)

**Comment by jodastephen** [comment]
Fixed by https://github.com/JodaOrg/joda-time/commit/e37246fb936b2c242812235dff53c749e18ec200#diff-480762ed7e0cb6175cb14bd289b7167eeac7ae35cf253725155eed73398da621
