### ISSUE TITLE
JRE tz data vs joda-time tz data

### ISSUE THREAD

**Issue by jahar-tyagi** [JodaOrg/joda-time#579]
Hi, 

We have  recently updated the tzData to - [tzdata2021e] in our JRE with the help of tZUpdater tool as recommended by [Oracle  ](https://www.oracle.com/java/technologies/javase/tzupdater-readme.html#ondemand).  But not updated the joda-time Jar. Still have jodatime-2.8.1. 
Now since tzData is already updated in JRE, will jodatime jar use the same JRE's tzData or its own data for timezone? Do they both (JRE and Joda-Time) should have same tzData? 

- jdk version 18.0_221. 
- jodatime version - 2.8.1

**Comment by jodastephen** [comment]
Joda-Time has its own time zone data. The latest version has 2021e - https://www.joda.org/joda-time/changes-report.html#a2.10.13
