### ISSUE TITLE
DateTimeZone.getDefault() is prone to race condition

### ISSUE THREAD

**Issue by spand** [JodaOrg/joda-time#587]
### Key information
- Joda-Time version: Latest

I am mostly just documenting the problem here since the library is no longer in active development but obviously it would be nice to get fixed.

### Problem description
`DateTimeZone.getDefault()` is specified to check in order:
1. `user.timezone` property
2. `java.util.TimeZone.getDefault()`
3. Use UTC

This is problematic because the `user.timezone` property is not fixed but can change as `java.util.TimeZone.getDefault()` is specified to set the `user.timezone` if it is missing. If `java.util.TimeZone.setDefault()` is called prior to `getDefault()` then it will never be set. In effect this means that `user.timezone` is set (quite unintuitively imo) on two conditions:
1. Provided by the user as -Duser.timezone
2. or picked up from the environment.

I believe and assume that the `DateTimeZone.getDefault()` checks `user.timezone` first because it is assumed to only be set in case 1.

### The Problem

Ok. So what is the problem? You might say
> Just call `java.util.TimeZone.setDefault()`" and at startup and Joda will use that

That is what we do currently. However, it seems that is not enough. We initially discovered this when adding the NewRelic agent to our production system but have since discovered that when running the jvm even just in debug mode in IDEA then `user.timezone` is set before even before the main method starts executing. In effect having jodatime getting stuck on the environment timezone and never checking `java.util.TimeZone.getDefault()`. I can only assume that the agents has a codepath that triggers `java.util.TimeZone.getDefault()` on startup.

### Proposed solution
Stop checking the user.timezone property. Instead use the following algorithm
1. Check a `org.joda.time.defaulttimezone` property if one really wants to override jodatimes default timezone from the commandline. Technically this is not needed for us but I assume the `user.timezone` check is present to override any prior calls to `java.util.TimeZone.setDefault()`.
2. `java.util.TimeZone.getDefault()` which will then in turn check user.timezone if needed.
3. Use UTC 

This should provide a stable algorithm free of races.

### Test case (In Kotlin. It doesnt happen in plain java)

```kotlin
import java.util.*
import org.joda.time.DateTimeZone

fun main() {
    System.out.println("user.timezone " + System.getProperty("user.timezone"))
    System.out.println("java.util.TimeZone.getDefault() = " + TimeZone.getDefault().id)
    System.out.println("user.timezone " + System.getProperty("user.timezone"))
}
```

When run nomally:
```
user.timezone null
java.util.TimeZone.getDefault() = Europe/Paris
user.timezone Europe/Paris

Process finished with exit code 0
```

In debug:
```
Connected to the target VM, address: '127.0.0.1:57990', transport: 'socket'
user.timezone Europe/Paris
java.util.TimeZone.getDefault() = Europe/Paris
user.timezone Europe/Paris
Disconnected from the target VM, address: '127.0.0.1:57990', transport: 'socket'

Process finished with exit code 0
```

**Comment by jodastephen** [comment]
Thanks for the detailed issue. I've made the change, although there is some risk of breaking users, I think that risk is small.

**Comment by jahar-tyagi** [comment]
Does it have any effect on application code? Though it is mentioned in Release note as:  _"In most cases this change will have no effect on application code, as 'user.timezone' will be picked up by 'TimeZone.getDefault()' instead. If you specifically need to stop Joda-Time calling 'TimeZone.getDefault()' then you will need to change to use the new system property 'org.joda.time.DateTimeZone.Timezone'"_

But this is little unclear to me.

**Comment by jodastephen** [comment]
Unless your application is very special/weird, just do nothing and everything will continue to work.

If your application is weird, and want to set the Joda-Time zone specifically, use `org.joda.time.DateTimeZone.Timezone'` on the command line instead of `user.timezone`

**Comment by jahar-tyagi** [comment]
Thanks for the clarification @jodastephen

**Comment by jahar-tyagi** [comment]
Is it possible that Joda uses the timezone information (tzdata) picked up from the environment or JRE directly using -Duser.timezone or any other config. So that every time we don't have to update tzDB in Joda?

**Comment by jodastephen** [comment]
That is not an option available in Joda-Time
