### ISSUE TITLE
flaky test 

### ISSUE THREAD

**Issue by bliu62** [JodaOrg/joda-time#588]
### Key information
- Joda-Time version 2.10.13
- Result of `TimeZone.getDefault()`
-sun.util.calendar.ZoneInfo[id="America/Chicago",offset=-21600000,dstSavings=3600000,useDaylight=true,transitions=235,lastRule=java.util.SimpleTimeZone[id=America/Chicago,offset=-21600000,dstSavings=3600000,useDayligh
- Result of `DateTimeZone.getDefault()`
- America/Chicago

### Problem description
I test Randoop on the Joda time project, and I find a flaky test ,dateTime6 
dateTime3 will produce the same string and different string sometimes  like

dateTime6   2565-05-02T17:34:00.571Z
dateTime3   2565-05-02T17:34:00.570Z

dateTime6   2565-05-02T17:39:50.396Z
dateTime3   2565-05-02T17:39:50.396Z
I think this is a flaky test which could revel the bug in org.joda.time.chrono.BuddhistChronology class
### Test case
       org.joda.time.chrono.BuddhistChronology buddhistChronology1 = org.joda.time.chrono.BuddhistChronology.getInstanceUTC();		      
       org.joda.time.DateTime dateTime3 = org.joda.time.DateTime.now((org.joda.time.Chronology) buddhistChronology1);
       org.joda.time.chrono.StrictChronology strictChronology4 = org.joda.time.chrono.StrictChronology.getInstance((org.joda.time.Chronology) buddhistChronology1);		    
       org.joda.time.DateTime dateTime6 = org.joda.time.DateTime.now((org.joda.time.Chronology) strictChronology4);
      org.junit.Assert.assertTrue("Contract failed: compareTo-equals on dateTime3 and dateTime6", (dateTime3.compareTo(dateTime6) == 0) == dateTime3.equals(dateTime6));

**Comment by jodastephen** [comment]
There is no bug here. You are comparing the result of `now()` called twice.
