### ISSUE TITLE
Updating global-tz in joda after global-tz is updated to tzdb 2022b

### ISSUE THREAD

**Issue by hagai-lvi** [JodaOrg/joda-time#621]
### Key information

- Joda-Time version: 2.10.14
- Result of `TimeZone.getDefault()` Irrelevant
- Result of `DateTimeZone.getDefault()` Irrelevant

### Problem description
Update joda's global-tz, after global-tz is updated to tzdb 2022b

tzdb is updated to version [2022b](https://mm.icann.org/pipermail/tz-announce/2022-August.txt):
>    Briefly:
     Chile's DST is delayed by a week in September 2022.
     Iran no longer observes DST after 2022.
     Rename Europe/Kiev to Europe/Kyiv.
     New zic -R option
     Vanguard form now uses %z.
     Finish moving duplicate-since-1970 zones to 'backzone'.
     New build option PACKRATLIST
     New tailored_tarballs target, replacing rearguard_tarballs
     
blocked by https://github.com/JodaOrg/global-tz/issues/5
opening this to follow and get notified when Joda is updated

**Comment by jodastephen** [comment]
See release [2.11.0](https://www.joda.org/joda-time/changes-report.html#a2.11.0).
