### ISSUE TITLE
Change Hebrew date formatting 

### ISSUE THREAD

**Issue by Arihol** [JodaOrg/joda-time#646]
The default way joda formats Hebrew dates isn’t the one universally used by Hebrew speakers. Two better  alternatives are  

- DD/MM/YYYY
>01/10/2022
- day (in numbers) in month (in letters) year (in numbers), written from right to left.
> 1 באוקטובר 2022

NOTE: I opened this issue because dates are formatted incorrectly on Lichess, a FOSS chess server that uses your library

**Comment by jodastephen** [comment]
Date formats like this are derived from data in Java itself, with Joda-Time not really getting involved.
