### ISSUE TITLE
Update to tz 2022e

### ISSUE THREAD

**Issue by qiangdavidliu** [JodaOrg/joda-time#662]
### Key information

- Joda-Time version: v2.11.2

### Problem description
tzdb 2022e has just been released as of `2022-10-11 11:13:02 -0700` ([link](https://github.com/eggert/tz/commit/c4eb3fcf2fc736b7924176cf9c3f9c305c398b8b)). Can we please get a release with these latest changes? Thanks!

### Test case
N/A

**Comment by jodastephen** [comment]
See release [2.12.0](https://www.joda.org/joda-time/changes-report.html#a2.11.2)
