### ISSUE TITLE
Windhoek timezone update

### ISSUE THREAD

**Issue by LiulangZhang** [JodaOrg/joda-time#675]
Hi
Windhoek has decided to continue with GMT+2 timezone from Oct 23th 2017 , but the current library windhoek's timezone will set to GMT+1 .

Do we have any release to address this issue ?
Thanks

**Comment by jodastephen** [comment]
Issues with timezone data should be sent to IANA TZDB. Joda-Time simply consumes the data from there. Do make sure that you check you are using the latest version of Joda-Time though!
