### ISSUE TITLE
Create a Tag on the latest release (v2.12.2)

### ISSUE THREAD

**Issue by tadashiya** [JodaOrg/joda-time#680]
Thank you for your work.
I found that `Release v2.12.2` is not tagged yet.
https://github.com/JodaOrg/joda-time/releases

Please make it the latest release. It's beneficial for users to catch up on your artifacts.

Thank you,
Tadashi Yamasaki

**Comment by jodastephen** [comment]
This should have all been automated, but for some reason the process did not complete correctly. I've done my best to create the release on GitHub, it isn't perfect but will have to do.

**Comment by tadashiya** [comment]
Thank you for your reply. I understand the situation.
Anyway, thanks for your work.
