### ISSUE TITLE
More arithmetic for Durations

### ISSUE THREAD

**Issue by bjoernpollex** [JodaOrg/joda-time#69]
I would like to have support for the following operations on `Duration`:

* `Duration.scale(double factor)` - stretch the duration by the given factor
  * maybe `mul(int factor)` and `div(int factor)` would also make sense
* `Duration.floor(ReadableDuration precision)` - round the duration down to the nearest multiple of `precision`
* `Duration.ceil(ReadableDuration precision)` - round the duration up to the nearest multiple of `precision`

If no one objects to such operations, I would be happy to fork and implement them.

**Comment by a7i7** [comment]
Is this issue still open? I would like to work on this

**Comment by jodastephen** [comment]
If you'd like to raise a PR for `dividedBy(long, RoundingMode)` I'd consider it.

**Comment by a7i7** [comment]
Hi. Here is the PR [379](https://github.com/JodaOrg/joda-time/pull/379) implementing the above method. Kindly have a look at it.
