### ISSUE TITLE
DateTimeZone#forID throws exception for ZoneOffset.UTC.getId()

### ISSUE THREAD

**Issue by sdonfro** [JodaOrg/joda-time#717]
The Java Time API uses Zone ID "Z" for ZoneOffset.UTC. This ID value is not supported by Joda-Time so a simple conversion like the following throws an IllegalArgumentException stating that "The datetime zone id 'Z' is not recognised".

`DateTimeZone.forID(ZoneOffset.UTC.getId())`

Ideally DateTimeZone.UTC would be returned in this case.

I am using joda-time 2.12.5 with OpenJDK 17.0.5.

**Comment by jodastephen** [comment]
Seems reasonable, although there are quite a few cases where a simple conversion won't work.
