### ISSUE TITLE
Crashes for the America/Ciudad_Juarez

### ISSUE THREAD

**Issue by sagarpatel288** [JodaOrg/joda-time#729]
### Key information

- 2.12.5 (Latest Joda-time library version)
- Result of `TimeZone.getDefault()` -> Crash.
- Result of `DateTimeZone.getDefault()` -> Crash.

### Problem description
In Android, For the `America/Ciudad_Juarez` timezone, it crashes when we try to call:
`DateTimeZone.forTimeZone(TimeZone.getDefault());`

### Test case
Set the timezone in an Android device as Mexico -> Ciudad_Juarez. 
Use any application that uses `DateTimeZone.forTimeZone(TimeZone.getDefault());` for the Mexico -> Ciudad_Juarez.

**Comment by jodastephen** [comment]
```
    DateTimeZone zone = DateTimeZone.forID("America/Ciudad_Juarez");
    System.out.println(zone);
```
This code works for me. I suspect this is an issue with the Android time zone provider, which isn't part of Joda-Time.
