### ISSUE TITLE
Calculation of  Duration between two DateTimes in March 2023 produces an incorrect result. 

### ISSUE THREAD

**Issue by werni38** [JodaOrg/joda-time#730]
### Key information

- Joda-Time version 2.12.5
- Result of `TimeZone.getDefault()`: sun.util.calendar.ZoneInfo[id="Europe/Zurich", ...
- Result of `DateTimeZone.getDefault()` : Europe/Zurich

### Problem description
Calculation of  Duration between two DateTimes in March 2023 produces an incorrect result. In particular the Duration between 2023-03-26 and 2023-03-27 produces 0 days instead of 1. However if Instants are used instead of DateTimes, the result is correct. A consequence is that March has only 
[Main.java.txt](https://github.com/JodaOrg/joda-time/files/11918513/Main.java.txt)
30 days when calculating the Duration between the DateTimes of 2023-03-01 and 2023-04-01.

### Test case
Output of the attached Java program:
Duration (DateTimes) 2023-03-26 - 2023-03-27 ->   82800000 msec  -> 1380 minutes -> 0 days
Duration (Instants)  2023-03-26 - 2023-03-27 ->   86400000 msec  -> 1440 minutes -> 1 days
ddays = 1
pdays = 1
[Main.java.txt](https://github.com/JodaOrg/joda-time/files/11918554/Main.java.txt)

**Comment by jodastephen** [comment]
This is behaving correctly. When using `DateTime` the time zone is taken into account, and there a full 24 hour day has not been completed. You are hiding this by using the formatter for output. Instead, just output the `DateTime`:

```
    System.out.println("Duration (DateTimes) " + startDate + " - " + endDate + " ->   " + durMillis + " msec  -> " +
        durMinutes + " minutes -> " + durDays + " days");
```
outputs
```
Duration (DateTimes) 2023-03-26T00:00:00.000Z - 2023-03-27T00:00:00.000+01:00 ->   82800000 msec  -> 1380 minutes -> 0 days
Duration (Instants)  2023-03-26T00:00:00.000Z - 2023-03-27T00:00:00.000Z ->   86400000 msec  -> 1440 minutes -> 1 days
```
As can be seen, the time-zone changes, thus only 23 hours pass which is not 1 day (by the definition of the method)
