### ISSUE TITLE
Publish to MVN central

### ISSUE THREAD

**Issue by alfredalbrecht** [JodaOrg/joda-time#738]
Hi joda-folks,
I just wanted to ask why the binary is not being published to mvn central anymore?

Latest published version I  see there is [2.12.5](https://mvnrepository.com/artifact/joda-time/joda-time/2.12.5).

Regards,
Alfred

**Comment by Taz03** [comment]
maybe coz thats the latest release?

**Comment by alfredalbrecht** [comment]
So true. Sorry, I think that evening something was wrong with my eyes/ brain.

**Comment by alfredalbrecht** [comment]
Done
