### ISSUE TITLE
Expand Range of Years

### ISSUE THREAD

**Issue by ABLEquitus** [JodaOrg/joda-time#769]
Currently, years must be in the range [-292275055,292278994].

It would be nice if joda-time was updated to allow for thousands of millions of years in the past, as I currently can't use the library for my RDF statements regarding fossils before the beginning year.

**Comment by ZacSweers** [comment]
Extremely curious what kinds of fossils you've predating the big bang

**Comment by ABLEquitus** [comment]
https://www.wikidata.org/wiki/Q21217611

https://www.wikidata.org/wiki/Q5884287


Big Bang = 13798 million years BCE

**Comment by jodastephen** [comment]
Sadly this is basically impossible without a complete redesign of Joda-Time. Maybe try using java.tim.*?

**Comment by ABLEquitus** [comment]
> Sadly this is basically impossible without a complete redesign of Joda-Time. Maybe try using java.tim.*?

Understood. Thanks man.
