### ISSUE TITLE
How to migrate Joda time Period API to Java time (java 8)?

### ISSUE THREAD

**Issue by solsau** [JodaOrg/joda-time#770]
I want to migrate JODA time period API to JAVA time (java 8).

Joda time period API supports both time and date.eg. It supports from milliseconds to year. But in java.time we have 2 separate functionality 1.Period which is date API and support from day to year 2.Duration is time API which supports from millisecond to hours. I am currently using Duration API but facing problem when I am using Duration for month eg. I want to add February month for which Duration.month is by default taking 30 days. Is there any solution available in java which supports both date and time API at same time?

I have tried using java.time period and duration API but both are having their specific limits. I want solution in java which supports both time and date API.

**Comment by jodastephen** [comment]
Use `PeriodDuration` from [ThreeTen-Extea](https://www.threeten.org/threeten-extra/).

**Comment by solsau** [comment]
[ThreeTen-Extea](https://www.threeten.org/threeten-extra/). is internally using joda.convert so Do we need maintain time zone related data. As joda-time requires time-zone related data.
